import type {
  DataMetaBase,
  DataValueType,
  Variant
} from '../runtime/types/primitive-types';

declare namespace _exports {
  export type Color = 
  | DataValueType<{}, DataMetaBase<'color'> & { 
    red: number,
    green: number,
    blue: number,
    alpha: number
  }>
}

type Color = _exports.Color;

declare const _exports: {
  color(red: number, green: number, blue: number, alpha: number): Variant<Color, 'color'>,
  'is-color'(val: any): val is Variant<Color, 'color'>,

  'orange': Color,
  'red': Color,
  'orange-red': Color,
  'tomato': Color,
  'dark-red': Color,
  'fire-brick': Color,
  'crimson': Color,
  'deep-pink': Color,
  'maroon': Color,
  'indian-red': Color,
  'medium-violet-red': Color,
  'violet-red': Color,
  'light-coral': Color,
  'hot-pink': Color,
  'pale-violet-red': Color,
  'light-pink': Color,
  'rosy-brown': Color,
  'pink': Color,
  'orchid': Color,
  'lavender-blush': Color,
  'snow': Color,
  'chocolate': Color,
  'saddle-brown': Color,
  'brown': Color,
  'dark-orange': Color,
  'coral': Color,
  'sienna': Color,
  'salmon': Color,
  'peru': Color,
  'dark-goldenrod': Color,
  'goldenrod': Color,
  'sandy-brown': Color,
  'light-salmon': Color,
  'dark-salmon': Color,
  'gold': Color,
  'yellow': Color,
  'olive': Color,
  'burlywood': Color,
  'tan': Color,
  'navajo-white': Color,
  'peach-puff': Color,
  'khaki': Color,
  'dark-khaki': Color,
  'moccasin': Color,
  'wheat': Color,
  'bisque': Color,
  'pale-goldenrod': Color,
  'blanched-almond': Color,
  'medium-goldenrod': Color,
  'papaya-whip': Color,
  'misty-rose': Color,
  'lemon-chiffon': Color,
  'antique-white': Color,
  'cornsilk': Color,
  'light-goldenrod-yellow': Color,
  'old-lace': Color,
  'linen': Color,
  'light-yellow': Color,
  'seashell': Color,
  'beige': Color,
  'floral-white': Color,
  'ivory': Color,
  'green': Color,
  'lawn-green': Color,
  'chartreuse': Color,
  'green-yellow': Color,
  'yellow-green': Color,
  'medium-forest-green': Color,
  'olive-drab': Color,
  'dark-olive-green': Color,
  'dark-sea-green': Color,
  'lime': Color,
  'dark-green': Color,
  'lime-green': Color,
  'forest-green': Color,
  'spring-green': Color,
  'medium-spring-green': Color,
  'sea-green': Color,
  'medium-sea-green': Color,
  'aquamarine': Color,
  'light-green': Color,
  'pale-green': Color,
  'medium-aquamarine': Color,
  'turquoise': Color,
  'light-sea-green': Color,
  'medium-turquoise': Color,
  'honeydew': Color,
  'mint-cream': Color,
  'royal-blue': Color,
  'dodger-blue': Color,
  'deep-sky-blue': Color,
  'cornflower-blue': Color,
  'steel-blue': Color,
  'light-sky-blue': Color,
  'dark-turquoise': Color,
  'cyan': Color,
  'aqua': Color,
  'dark-cyan': Color,
  'teal': Color,
  'sky-blue': Color,
  'cadet-blue': Color,
  'dark-slate-gray': Color,
  'dark-slate-grey': Color,
  'light-slate-gray': Color,
  'light-slate-grey': Color,
  'slate-gray': Color,
  'slate-grey': Color,
  'light-steel-blue': Color,
  'light-blue': Color,
  'powder-blue': Color,
  'pale-turquoise': Color,
  'light-cyan': Color,
  'alice-blue': Color,
  'azure': Color,
  'medium-blue': Color,
  'dark-blue': Color,
  'midnight-blue': Color,
  'navy': Color,
  'blue': Color,
  'indigo': Color,
  'blue-violet': Color,
  'medium-slate-blue': Color,
  'slate-blue': Color,
  'purple': Color,
  'dark-slate-blue': Color,
  'dark-violet': Color,
  'dark-orchid': Color,
  'medium-purple': Color,
  'medium-orchid': Color,
  'magenta': Color,
  'fuchsia': Color,
  'dark-magenta': Color,
  'violet': Color,
  'plum': Color,
  'lavender': Color,
  'thistle': Color,
  'ghost-white': Color,
  'white': Color,
  'white-smoke': Color,
  'gainsboro': Color,
  'light-gray': Color,
  'light-grey': Color,
  'silver': Color,
  'gray': Color,
  'grey': Color,
  'dark-gray': Color,
  'dark-grey': Color,
  'dim-gray': Color,
  'dim-grey': Color,
  'black': Color,
  'transparent': Color,
  'rebecca-purple': Color,
  
}
export = _exports;