#!/bin/bash

set -e
set -o nounset
#set -x

ORIG_FILE=`readlink -f $1`
pushd "$(dirname "$0")/../.." > /dev/null
FILE=`realpath --relative-to="." "$ORIG_FILE"`

NODE="node -max-old-space-size=8192"
SYMLINK_NAME=`basename "$0"`
PHASE="$SYMLINK_NAME"
PYRET_JARR="build/$PHASE/pyret.jarr"

if [ 1 -gt "$#" ]
then
    echo "Expecting 1 argument; received $#"
    echo "Usage: $PHASE file.arr [args]"
    popd > /dev/null
    exit 1
fi

if [ ! -e $PYRET_JARR ]
then
    echo "missing pyret.jarr file. run: make $PHASE"
    popd > /dev/null
    exit 1
fi

if [ ! -e $FILE ]
then
    echo "Error: No such file: $FILE"
    popd > /dev/null
    exit 1
fi

shift 1

if [ "$#" -gt 0 ]
then
    $NODE $PYRET_JARR -no-display-progress --run $FILE - "$@"
else
    $NODE $PYRET_JARR -no-display-progress --run $FILE
fi

popd > /dev/null
