#!/bin/sh

NODE="node -max-old-space-size=8192"

SYMLINK_NAME=`basename "$0"`
SELF_NAME=`basename $(readlink -f $0)`

if [ "$SYMLINK_NAME" = "$SELF_NAME" ]
then
    echo "This script cannot be run directly. Use either phase0, phaseA, phaseB, or phaseC."
    exit 1
fi

PHASE="$SYMLINK_NAME"
PYRET_JARR="build/$PHASE/pyret.jarr"
FILE=$1

if [ "$#" -ne 1 ]
then
    echo "Expecting 1 argument; received $#"
    echo "Usage: $PHASE file.arr"
    exit 1
fi

if [ ! -e $PYRET_JARR ]
then
    echo "missing pyret.jarr file. run: make $PHASE"
    exit 1
fi

if [ ! -e $FILE ]
then
    echo "Error: No such file: $FILE"
    exit 1
fi

$NODE $PYRET_JARR -no-display-progress --run "$@"
