import "./tests/test-strings.arr" as _
import "./tests/test-numbers.arr" as _
import "./tests/test-errors.arr" as _
import "./tests/test-import.arr" as _
import "./tests/test-sets.arr" as _
import "./tests/test-binops.arr" as _
import "./tests/test-letrec.arr" as _
import "./tests/test-output.arr" as _
import "./tests/test-array.arr" as _
import "./tests/test-constructors.arr" as _
import "./tests/test-contracts.arr" as _
import "./tests/test-s-exp.arr" as _
import "./tests/test-refs.arr" as _
import "./tests/test-equality.arr" as _
import "./tests/test-refined-refs.arr" as _
import "./tests/test-match.arr" as _
import "./tests/test-lists.arr" as _
import "./tests/test-cases.arr" as _
import "./tests/test-rec.arr" as _
import "./tests/test-compile-errors.arr" as _
import "./tests/test-file.arr" as _
