import file("./tests/test-strings.arr") as _
import file("./tests/test-numbers.arr") as _
import file("./tests/test-errors.arr") as _
#import file("./tests/test-import.arr") as _
import file("./tests/test-sets.arr") as _
import file("./tests/test-binops.arr") as _
import file("./tests/test-letrec.arr") as _
import file("./tests/test-torepr.arr") as _
import file("./tests/test-array.arr") as _
import file("./tests/test-constructors.arr") as _
import file("./tests/test-contracts.arr") as _
import file("./tests/test-s-exp.arr") as _
import file("./tests/test-json.arr") as _
import file("./tests/test-refs.arr") as _
import file("./tests/test-equality.arr") as _
import file("./tests/test-refined-refs.arr") as _
import file("./tests/test-match.arr") as _
import file("./tests/test-lists.arr") as _
import file("./tests/test-cases.arr") as _
import file("./tests/test-rec.arr") as _
import file("./tests/test-compile-errors.arr") as _
import file("./tests/test-file.arr") as _
import file("./tests/test-path.arr") as _
import file("./tests/test-repl.arr") as _
import file("./tests/test-file-locators.arr") as _
import file("./tests/test-builtin-locator.arr") as _

