import file("./regression/empty-concat-list-and-block.arr") as _
import file("./regression/random-arg-typecheck.arr") as _
import file("./regression/immediate-app-return-ann.arr") as _
import file("./regression/zero.arr") as _
import file("./regression/curried-funs.arr") as _
import file("./regression/is-not-uses-equal-always.arr") as _
import file("./regression/double-desugar-extend.arr") as _
import file("./regression/pretty-print-instantiate.arr") as _
import file("./regression/random-bogus-range.arr") as _
import file("./regression/seq-of-lettable.arr") as _
import file("./regression/cases-expr-parse.arr") as _
import file("./regression/method-scope.arr") as _
import file("./regression/check-scope.arr") as _
import file("./regression/anf-of-vars.arr") as _
import file("./regression/var-statement.arr") as _
import file("./regression/string-dict-equality.arr") as _
import file("./regression/stack-safe-each-loop.arr") as _
import file("./regression/proto-fields.arr") as _
import file("./regression/toplevel-data.arr") as _
import file("./regression/bogus-global-type-name.arr") as _
import file("./regression/duplicate-check-block-report.arr") as _
import file("./regression/tail-recursion-arg-order.arr") as _
import file("./regression/escaping-module-uris.arr") as _
import file("./regression/flat-refinement.arr") as _
