import file("./tests/test-builtin-locator.arr") as _
import file("./tests/test-compile-lib.arr") as _
import file("./tests/test-include.arr") as _
import file("./tests/test-examples.arr") as _
import file("./tests/test-string-dict.arr") as _
import file("./tests/test-dup-names.arr") as _
import file("./tests/test-tables.arr") as _
import file("./tests/test-tuple.arr") as _
import file("./tests/test-reactor.arr") as _
import file("./tests/test-tail-call.arr") as _
import file("./tests/test-parse.arr") as _
import file("./tests/test-parse-errors.arr") as _
