import file("./tests/test-adaptive-simpson.arr") as _
import file("./tests/test-array.arr") as _
import file("./tests/test-binops.arr") as _
import file("./tests/test-cases.arr") as _
import file("./tests/test-constructors.arr") as _
import file("./tests/test-dup-names.arr") as _
import file("./tests/test-equality.arr") as _
import file("./tests/test-examples.arr") as _
import file("./tests/test-format.arr") as _
import file("./tests/test-import.arr") as _
import file("./tests/test-json.arr") as _
import file("./tests/test-letrec.arr") as _
import file("./tests/test-lists.arr") as _
import file("./tests/test-match.arr") as _
import file("./tests/test-math.arr") as _
import file("./tests/test-numbers.arr") as _
import file("./tests/test-output.arr") as _
import file("./tests/test-refined-refs.arr") as _
import file("./tests/test-refs.arr") as _
import file("./tests/test-roughnum.arr") as _
import file("./tests/test-sets.arr") as _
import file("./tests/test-statistics.arr") as _
import file("./tests/test-str-dict.arr") as _
import file("./tests/test-string-dict.arr") as _
import file("./tests/test-strings.arr") as _
import file("./tests/test-tables.arr") as _
import file("./tests/test-within.arr") as _
