import file("./tests/test-refs.arr") as _
import file("./tests/test-equality.arr") as _
import file("./tests/test-refined-refs.arr") as _
import file("./tests/test-match.arr") as _
import file("./tests/test-lists.arr") as _
import file("./tests/test-math.arr") as _
import file("./tests/test-statistics.arr") as _
import file("./tests/test-cases.arr") as _
import file("./tests/test-rec.arr") as _
import file("./tests/test-compile-errors.arr") as _
import file("./tests/test-well-formed.arr") as _
import file("./tests/test-file.arr") as _
import file("./tests/test-path.arr") as _
import file("./tests/test-repl.arr") as _
import file("./tests/test-file-locators.arr") as _
