import file("./tests/test-strings.arr") as _
import file("./tests/test-format.arr") as _
import file("./tests/test-numbers.arr") as _
import file("./tests/test-errors.arr") as _
import file("./tests/test-error-rendering.arr") as _
import file("./tests/test-import.arr") as _
import file("./tests/test-sets.arr") as _
import file("./tests/test-binops.arr") as _
import file("./tests/test-letrec.arr") as _
import file("./tests/test-output.arr") as _
import file("./tests/test-array.arr") as _
import file("./tests/test-constructors.arr") as _
import file("./tests/test-contracts.arr") as _
import file("./tests/test-s-exp.arr") as _
import file("./tests/test-json.arr") as _
