# THIS FILE IS AUTOMATICALLY GENERATED FROM autogenerate.arr. PLEASE DO NOT EDIT.
provide *

include ast
include lists
include option
import global as _
import base as _
shadow default-iter-visitor =
  {
    method option(self, opt):
      cases(Option) opt: | none => true | some( v) => v.visit(self) end
    end,
    method list(self, lst):
      cases(List) lst:
        | empty => true
        | link( f,  r) => f.visit(self) and self.list(r)
      end
    end,
    method s-underscore(self, l): true end,
    method s-name(self, l, s): true end,
    method s-global(self, s): true end,
    method s-type-global(self, s): true end,
    method s-atom(self, base, serial): true end,
    method app-info-c(self, is-recursive, is-tail): true end,
    method s-program(self, l, _provide, provided-types, imports, block):
      _provide.visit(self)
      and
      provided-types.visit(self) and self.list(imports) and block.visit(self)
    end,
    method s-include(self, l, mod): mod.visit(self) end,
    method s-import(self, l, file, name):
      file.visit(self) and name.visit(self)
    end,
    method s-import-types(self, l, file, name, types):
      file.visit(self) and name.visit(self) and types.visit(self)
    end,
    method s-import-fields(self, l, fields, file):
      self.list(fields) and file.visit(self)
    end,
    method s-import-complete(
        self,
        l,
        values,
        types,
        import-type,
        vals-name,
        types-name
      ):
      self.list(values)
      and
      self.list(types) and import-type.visit(self) and vals-name.visit(self)
        and
        types-name.visit(self)
    end,
    method p-value(self, l, v, ann): v.visit(self) and ann.visit(self) end,
    method p-alias(self, l, in-name, out-name, mod):
      in-name.visit(self) and out-name.visit(self) and self.option(mod)
    end,
    method p-data(self, l, d, mod): d.visit(self) and self.option(mod) end,
    method s-provide(self, l, block): block.visit(self) end,
    method s-provide-complete(self, l, values, aliases, data-definitions):
      self.list(values) and self.list(aliases) and self.list(data-definitions)
    end,
    method s-provide-all(self, l): true end,
    method s-provide-none(self, l): true end,
    method s-provide-types(self, l, ann): self.list(ann) end,
    method s-provide-types-all(self, l): true end,
    method s-provide-types-none(self, l): true end,
    method s-const-import(self, l, mod): true end,
    method s-special-import(self, l, kind, args): true end,
    method h-use-loc(self, l): true end,
    method s-let-bind(self, l, b, value):
      b.visit(self) and value.visit(self)
    end,
    method s-var-bind(self, l, b, value):
      b.visit(self) and value.visit(self)
    end,
    method s-letrec-bind(self, l, b, value):
      b.visit(self) and value.visit(self)
    end,
    method s-type-bind(self, l, name, params, ann):
      name.visit(self) and self.list(params) and ann.visit(self)
    end,
    method s-newtype-bind(self, l, name, namet):
      name.visit(self) and namet.visit(self)
    end,
    method s-defined-value(self, name, value): value.visit(self) end,
    method s-defined-var(self, name, id): id.visit(self) end,
    method s-defined-type(self, name, typ): typ.visit(self) end,
    method s-module(
        self,
        l,
        answer,
        defined-values,
        defined-types,
        provided-values,
        provided-types,
        checks
      ):
      answer.visit(self)
      and
      self.list(defined-values) and self.list(defined-types)
        and
        provided-values.visit(self) and self.list(provided-types)
        and
        checks.visit(self)
    end,
    method s-template(self, l): true end,
    method s-type-let-expr(self, l, binds, body, blocky):
      self.list(binds) and body.visit(self)
    end,
    method s-let-expr(self, l, binds, body, blocky):
      self.list(binds) and body.visit(self)
    end,
    method s-letrec(self, l, binds, body, blocky):
      self.list(binds) and body.visit(self)
    end,
    method s-hint-exp(self, l, hints, exp):
      self.list(hints) and exp.visit(self)
    end,
    method s-instantiate(self, l, expr, params):
      expr.visit(self) and self.list(params)
    end,
    method s-block(self, l, stmts): self.list(stmts) end,
    method s-user-block(self, l, body): body.visit(self) end,
    method s-fun(
        self,
        l,
        name,
        params,
        args,
        ann,
        doc,
        body,
        _check-loc,
        _check,
        blocky
      ):
      self.list(params)
      and
      self.list(args) and ann.visit(self) and body.visit(self)
        and
        self.option(_check)
    end,
    method s-type(self, l, name, params, ann):
      name.visit(self) and self.list(params) and ann.visit(self)
    end,
    method s-newtype(self, l, name, namet):
      name.visit(self) and namet.visit(self)
    end,
    method s-var(self, l, name, value):
      name.visit(self) and value.visit(self)
    end,
    method s-rec(self, l, name, value):
      name.visit(self) and value.visit(self)
    end,
    method s-let(self, l, name, value, keyword-val):
      name.visit(self) and value.visit(self)
    end,
    method s-ref(self, l, ann): self.option(ann) end,
    method s-contract(self, l, name, ann):
      name.visit(self) and ann.visit(self)
    end,
    method s-when(self, l, test, block, blocky):
      test.visit(self) and block.visit(self)
    end,
    method s-assign(self, l, id, value):
      id.visit(self) and value.visit(self)
    end,
    method s-if-pipe(self, l, branches, blocky): self.list(branches) end,
    method s-if-pipe-else(self, l, branches, _else, blocky):
      self.list(branches) and _else.visit(self)
    end,
    method s-if(self, l, branches, blocky): self.list(branches) end,
    method s-if-else(self, l, branches, _else, blocky):
      self.list(branches) and _else.visit(self)
    end,
    method s-cases(self, l, typ, val, branches, blocky):
      typ.visit(self) and val.visit(self) and self.list(branches)
    end,
    method s-cases-else(self, l, typ, val, branches, _else, blocky):
      typ.visit(self)
      and
      val.visit(self) and self.list(branches) and _else.visit(self)
    end,
    method s-op(self, l, op-l, op, left, right):
      left.visit(self) and right.visit(self)
    end,
    method s-check-test(self, l, op, refinement, left, right):
      op.visit(self)
      and
      self.option(refinement) and left.visit(self) and self.option(right)
    end,
    method s-check-expr(self, l, expr, ann):
      expr.visit(self) and ann.visit(self)
    end,
    method s-paren(self, l, expr): expr.visit(self) end,
    method s-lam(
        self,
        l,
        name,
        params,
        args,
        ann,
        doc,
        body,
        _check-loc,
        _check,
        blocky
      ):
      self.list(params)
      and
      self.list(args) and ann.visit(self) and body.visit(self)
        and
        self.option(_check)
    end,
    method s-method(
        self,
        l,
        name,
        params,
        args,
        ann,
        doc,
        body,
        _check-loc,
        _check,
        blocky
      ):
      self.list(params)
      and
      self.list(args) and ann.visit(self) and body.visit(self)
        and
        self.option(_check)
    end,
    method s-extend(self, l, supe, fields):
      supe.visit(self) and self.list(fields)
    end,
    method s-update(self, l, supe, fields):
      supe.visit(self) and self.list(fields)
    end,
    method s-tuple(self, l, fields): self.list(fields) end,
    method s-tuple-get(self, l, tup, index, index-loc): tup.visit(self) end,
    method s-obj(self, l, fields): self.list(fields) end,
    method s-array(self, l, values): self.list(values) end,
    method s-construct(self, l, modifier, constructor, values):
      modifier.visit(self) and constructor.visit(self) and self.list(values)
    end,
    method s-app(self, l, _fun, args): _fun.visit(self) and self.list(args) end,
    method s-app-enriched(self, l, _fun, args, app-info):
      _fun.visit(self) and self.list(args) and app-info.visit(self)
    end,
    method s-prim-app(self, l, _fun, args): self.list(args) end,
    method s-prim-val(self, l, name): true end,
    method s-id(self, l, id): id.visit(self) end,
    method s-id-var(self, l, id): id.visit(self) end,
    method s-id-letrec(self, l, id, safe): id.visit(self) end,
    method s-undefined(self, l): true end,
    method s-srcloc(self, l, loc): true end,
    method s-num(self, l, n): true end,
    method s-frac(self, l, num, den): true end,
    method s-rfrac(self, l, num, den): true end,
    method s-bool(self, l, b): true end,
    method s-str(self, l, s): true end,
    method s-dot(self, l, obj, field): obj.visit(self) end,
    method s-get-bang(self, l, obj, field): obj.visit(self) end,
    method s-bracket(self, l, obj, key): obj.visit(self) and key.visit(self) end,
    method s-data(
        self,
        l,
        name,
        params,
        mixins,
        variants,
        shared-members,
        _check-loc,
        _check
      ):
      self.list(params)
      and
      self.list(mixins) and self.list(variants) and self.list(shared-members)
        and
        self.option(_check)
    end,
    method s-data-expr(
        self,
        l,
        name,
        namet,
        params,
        mixins,
        variants,
        shared-members,
        _check-loc,
        _check
      ):
      namet.visit(self)
      and
      self.list(params) and self.list(mixins) and self.list(variants)
        and
        self.list(shared-members) and self.option(_check)
    end,
    method s-for(self, l, iterator, bindings, ann, body, blocky):
      iterator.visit(self)
      and
      self.list(bindings) and ann.visit(self) and body.visit(self)
    end,
    method s-check(self, l, name, body, keyword-check): body.visit(self) end,
    method s-reactor(self, l, fields): self.list(fields) end,
    method s-table-extend(self, l, column-binds, extensions):
      column-binds.visit(self) and self.list(extensions)
    end,
    method s-table-update(self, l, column-binds, updates):
      column-binds.visit(self) and self.list(updates)
    end,
    method s-table-select(self, l, columns, table):
      self.list(columns) and table.visit(self)
    end,
    method s-table-order(self, l, table, ordering):
      table.visit(self) and self.list(ordering)
    end,
    method s-table-filter(self, l, column-binds, predicate):
      column-binds.visit(self) and predicate.visit(self)
    end,
    method s-table-extract(self, l, column, table):
      column.visit(self) and table.visit(self)
    end,
    method s-table(self, l, headers, rows):
      self.list(headers) and self.list(rows)
    end,
    method s-load-table(self, l, headers, spec):
      self.list(headers) and self.list(spec)
    end,
    method s-spy-block(self, l, message, contents):
      self.option(message) and self.list(contents)
    end,
    method s-table-row(self, l, elems): self.list(elems) end,
    method s-spy-name(self, l, name): name.visit(self) end,
    method s-spy-expr(self, l, name, value): value.visit(self) end,
    method s-construct-normal(self): true end,
    method s-construct-lazy(self): true end,
    method s-bind(self, l, shadows, id, ann):
      id.visit(self) and ann.visit(self)
    end,
    method s-tuple-bind(self, l, fields, as-name):
      self.list(fields) and self.option(as-name)
    end,
    method s-data-field(self, l, name, value): value.visit(self) end,
    method s-mutable-field(self, l, name, ann, value):
      ann.visit(self) and value.visit(self)
    end,
    method s-method-field(
        self,
        l,
        name,
        params,
        args,
        ann,
        doc,
        body,
        _check-loc,
        _check,
        blocky
      ):
      self.list(params)
      and
      self.list(args) and ann.visit(self) and body.visit(self)
        and
        self.option(_check)
    end,
    method s-field-name(self, l, name, ann): ann.visit(self) end,
    method s-for-bind(self, l, bind, value):
      bind.visit(self) and value.visit(self)
    end,
    method s-column-binds(self, l, binds, table):
      self.list(binds) and table.visit(self)
    end,
    method ASCENDING(self): true end,
    method DESCENDING(self): true end,
    method s-column-sort(self, l, column, direction):
      column.visit(self) and direction.visit(self)
    end,
    method s-table-extend-field(self, l, name, value, ann):
      value.visit(self) and ann.visit(self)
    end,
    method s-table-extend-reducer(self, l, name, reducer, col, ann):
      reducer.visit(self) and col.visit(self) and ann.visit(self)
    end,
    method s-sanitize(self, l, name, sanitizer):
      name.visit(self) and sanitizer.visit(self)
    end,
    method s-table-src(self, l, src): src.visit(self) end,
    method s-normal(self): true end,
    method s-mutable(self): true end,
    method s-variant-member(self, l, member-type, bind):
      member-type.visit(self) and bind.visit(self)
    end,
    method s-variant(self, l, constr-loc, name, members, with-members):
      self.list(members) and self.list(with-members)
    end,
    method s-singleton-variant(self, l, name, with-members):
      self.list(with-members)
    end,
    method s-if-branch(self, l, test, body):
      test.visit(self) and body.visit(self)
    end,
    method s-if-pipe-branch(self, l, test, body):
      test.visit(self) and body.visit(self)
    end,
    method s-cases-bind-ref(self): true end,
    method s-cases-bind-normal(self): true end,
    method s-cases-bind(self, l, field-type, bind):
      field-type.visit(self) and bind.visit(self)
    end,
    method s-cases-branch(self, l, pat-loc, name, args, body):
      self.list(args) and body.visit(self)
    end,
    method s-singleton-cases-branch(self, l, pat-loc, name, body):
      body.visit(self)
    end,
    method s-op-is(self, l): true end,
    method s-op-is-roughly(self, l): true end,
    method s-op-is-op(self, l, op): true end,
    method s-op-is-not(self, l): true end,
    method s-op-is-not-op(self, l, op): true end,
    method s-op-satisfies(self, l): true end,
    method s-op-satisfies-not(self, l): true end,
    method s-op-raises(self, l): true end,
    method s-op-raises-other(self, l): true end,
    method s-op-raises-not(self, l): true end,
    method s-op-raises-satisfies(self, l): true end,
    method s-op-raises-violates(self, l): true end,
    method a-blank(self): true end,
    method a-any(self, l): true end,
    method a-name(self, l, id): id.visit(self) end,
    method a-type-var(self, l, id): id.visit(self) end,
    method a-arrow(self, l, args, ret, use-parens):
      self.list(args) and ret.visit(self)
    end,
    method a-arrow-argnames(self, l, args, ret, use-parens):
      self.list(args) and ret.visit(self)
    end,
    method a-method(self, l, args, ret): self.list(args) and ret.visit(self) end,
    method a-record(self, l, fields): self.list(fields) end,
    method a-tuple(self, l, fields): self.list(fields) end,
    method a-app(self, l, ann, args): ann.visit(self) and self.list(args) end,
    method a-pred(self, l, ann, exp): ann.visit(self) and exp.visit(self) end,
    method a-dot(self, l, obj, field): obj.visit(self) end,
    method a-checked(self, checked, residual):
      checked.visit(self) and residual.visit(self)
    end,
    method a-field(self, l, name, ann): ann.visit(self) end
  }
shadow default-map-visitor =
  {
    method option(self, opt):
      cases(Option) opt: | none => none | some( v) => some(v.visit(self)) end
    end,
    method list(self, lst):
      cases(List) lst:
        | empty => empty
        | link( f,  r) => link(f.visit(self), self.list(r))
      end
    end,
    method s-underscore(self, l): s-underscore(l) end,
    method s-name(self, l, s): s-name(l, s) end,
    method s-global(self, s): s-global(s) end,
    method s-type-global(self, s): s-type-global(s) end,
    method s-atom(self, base, serial): s-atom(base, serial) end,
    method app-info-c(self, is-recursive, is-tail):
      app-info-c(is-recursive, is-tail)
    end,
    method s-program(self, l, _provide, provided-types, imports, block):
      s-program(l,
        _provide.visit(self),
        provided-types.visit(self),
        self.list(imports),
        block.visit(self))
    end,
    method s-include(self, l, mod): s-include(l, mod.visit(self)) end,
    method s-import(self, l, file, name):
      s-import(l, file.visit(self), name.visit(self))
    end,
    method s-import-types(self, l, file, name, types):
      s-import-types(l, file.visit(self), name.visit(self), types.visit(self))
    end,
    method s-import-fields(self, l, fields, file):
      s-import-fields(l, self.list(fields), file.visit(self))
    end,
    method s-import-complete(
        self,
        l,
        values,
        types,
        import-type,
        vals-name,
        types-name
      ):
      s-import-complete(l,
        self.list(values),
        self.list(types),
        import-type.visit(self),
        vals-name.visit(self),
        types-name.visit(self))
    end,
    method p-value(self, l, v, ann):
      p-value(l, v.visit(self), ann.visit(self))
    end,
    method p-alias(self, l, in-name, out-name, mod):
      p-alias(l, in-name.visit(self), out-name.visit(self), self.option(mod))
    end,
    method p-data(self, l, d, mod):
      p-data(l, d.visit(self), self.option(mod))
    end,
    method s-provide(self, l, block): s-provide(l, block.visit(self)) end,
    method s-provide-complete(self, l, values, aliases, data-definitions):
      s-provide-complete(l,
        self.list(values),
        self.list(aliases),
        self.list(data-definitions))
    end,
    method s-provide-all(self, l): s-provide-all(l) end,
    method s-provide-none(self, l): s-provide-none(l) end,
    method s-provide-types(self, l, ann): s-provide-types(l, self.list(ann)) end,
    method s-provide-types-all(self, l): s-provide-types-all(l) end,
    method s-provide-types-none(self, l): s-provide-types-none(l) end,
    method s-const-import(self, l, mod): s-const-import(l, mod) end,
    method s-special-import(self, l, kind, args):
      s-special-import(l, kind, args)
    end,
    method h-use-loc(self, l): h-use-loc(l) end,
    method s-let-bind(self, l, b, value):
      s-let-bind(l, b.visit(self), value.visit(self))
    end,
    method s-var-bind(self, l, b, value):
      s-var-bind(l, b.visit(self), value.visit(self))
    end,
    method s-letrec-bind(self, l, b, value):
      s-letrec-bind(l, b.visit(self), value.visit(self))
    end,
    method s-type-bind(self, l, name, params, ann):
      s-type-bind(l, name.visit(self), self.list(params), ann.visit(self))
    end,
    method s-newtype-bind(self, l, name, namet):
      s-newtype-bind(l, name.visit(self), namet.visit(self))
    end,
    method s-defined-value(self, name, value):
      s-defined-value(name, value.visit(self))
    end,
    method s-defined-var(self, name, id):
      s-defined-var(name, id.visit(self))
    end,
    method s-defined-type(self, name, typ):
      s-defined-type(name, typ.visit(self))
    end,
    method s-module(
        self,
        l,
        answer,
        defined-values,
        defined-types,
        provided-values,
        provided-types,
        checks
      ):
      s-module(l,
        answer.visit(self),
        self.list(defined-values),
        self.list(defined-types),
        provided-values.visit(self),
        self.list(provided-types),
        checks.visit(self))
    end,
    method s-template(self, l): s-template(l) end,
    method s-type-let-expr(self, l, binds, body, blocky):
      s-type-let-expr(l, self.list(binds), body.visit(self), blocky)
    end,
    method s-let-expr(self, l, binds, body, blocky):
      s-let-expr(l, self.list(binds), body.visit(self), blocky)
    end,
    method s-letrec(self, l, binds, body, blocky):
      s-letrec(l, self.list(binds), body.visit(self), blocky)
    end,
    method s-hint-exp(self, l, hints, exp):
      s-hint-exp(l, self.list(hints), exp.visit(self))
    end,
    method s-instantiate(self, l, expr, params):
      s-instantiate(l, expr.visit(self), self.list(params))
    end,
    method s-block(self, l, stmts): s-block(l, self.list(stmts)) end,
    method s-user-block(self, l, body): s-user-block(l, body.visit(self)) end,
    method s-fun(
        self,
        l,
        name,
        params,
        args,
        ann,
        doc,
        body,
        _check-loc,
        _check,
        blocky
      ):
      s-fun(l,
        name,
        self.list(params),
        self.list(args),
        ann.visit(self),
        doc,
        body.visit(self),
        _check-loc,
        self.option(_check),
        blocky)
    end,
    method s-type(self, l, name, params, ann):
      s-type(l, name.visit(self), self.list(params), ann.visit(self))
    end,
    method s-newtype(self, l, name, namet):
      s-newtype(l, name.visit(self), namet.visit(self))
    end,
    method s-var(self, l, name, value):
      s-var(l, name.visit(self), value.visit(self))
    end,
    method s-rec(self, l, name, value):
      s-rec(l, name.visit(self), value.visit(self))
    end,
    method s-let(self, l, name, value, keyword-val):
      s-let(l, name.visit(self), value.visit(self), keyword-val)
    end,
    method s-ref(self, l, ann): s-ref(l, self.option(ann)) end,
    method s-contract(self, l, name, ann):
      s-contract(l, name.visit(self), ann.visit(self))
    end,
    method s-when(self, l, test, block, blocky):
      s-when(l, test.visit(self), block.visit(self), blocky)
    end,
    method s-assign(self, l, id, value):
      s-assign(l, id.visit(self), value.visit(self))
    end,
    method s-if-pipe(self, l, branches, blocky):
      s-if-pipe(l, self.list(branches), blocky)
    end,
    method s-if-pipe-else(self, l, branches, _else, blocky):
      s-if-pipe-else(l, self.list(branches), _else.visit(self), blocky)
    end,
    method s-if(self, l, branches, blocky):
      s-if(l, self.list(branches), blocky)
    end,
    method s-if-else(self, l, branches, _else, blocky):
      s-if-else(l, self.list(branches), _else.visit(self), blocky)
    end,
    method s-cases(self, l, typ, val, branches, blocky):
      s-cases(l, typ.visit(self), val.visit(self), self.list(branches), blocky)
    end,
    method s-cases-else(self, l, typ, val, branches, _else, blocky):
      s-cases-else(l,
        typ.visit(self),
        val.visit(self),
        self.list(branches),
        _else.visit(self),
        blocky)
    end,
    method s-op(self, l, op-l, op, left, right):
      s-op(l, op-l, op, left.visit(self), right.visit(self))
    end,
    method s-check-test(self, l, op, refinement, left, right):
      s-check-test(l,
        op.visit(self),
        self.option(refinement),
        left.visit(self),
        self.option(right))
    end,
    method s-check-expr(self, l, expr, ann):
      s-check-expr(l, expr.visit(self), ann.visit(self))
    end,
    method s-paren(self, l, expr): s-paren(l, expr.visit(self)) end,
    method s-lam(
        self,
        l,
        name,
        params,
        args,
        ann,
        doc,
        body,
        _check-loc,
        _check,
        blocky
      ):
      s-lam(l,
        name,
        self.list(params),
        self.list(args),
        ann.visit(self),
        doc,
        body.visit(self),
        _check-loc,
        self.option(_check),
        blocky)
    end,
    method s-method(
        self,
        l,
        name,
        params,
        args,
        ann,
        doc,
        body,
        _check-loc,
        _check,
        blocky
      ):
      s-method(l,
        name,
        self.list(params),
        self.list(args),
        ann.visit(self),
        doc,
        body.visit(self),
        _check-loc,
        self.option(_check),
        blocky)
    end,
    method s-extend(self, l, supe, fields):
      s-extend(l, supe.visit(self), self.list(fields))
    end,
    method s-update(self, l, supe, fields):
      s-update(l, supe.visit(self), self.list(fields))
    end,
    method s-tuple(self, l, fields): s-tuple(l, self.list(fields)) end,
    method s-tuple-get(self, l, tup, index, index-loc):
      s-tuple-get(l, tup.visit(self), index, index-loc)
    end,
    method s-obj(self, l, fields): s-obj(l, self.list(fields)) end,
    method s-array(self, l, values): s-array(l, self.list(values)) end,
    method s-construct(self, l, modifier, constructor, values):
      s-construct(l,
        modifier.visit(self),
        constructor.visit(self),
        self.list(values))
    end,
    method s-app(self, l, _fun, args):
      s-app(l, _fun.visit(self), self.list(args))
    end,
    method s-app-enriched(self, l, _fun, args, app-info):
      s-app-enriched(l, _fun.visit(self), self.list(args), app-info.visit(self))
    end,
    method s-prim-app(self, l, _fun, args):
      s-prim-app(l, _fun, self.list(args))
    end,
    method s-prim-val(self, l, name): s-prim-val(l, name) end,
    method s-id(self, l, id): s-id(l, id.visit(self)) end,
    method s-id-var(self, l, id): s-id-var(l, id.visit(self)) end,
    method s-id-letrec(self, l, id, safe):
      s-id-letrec(l, id.visit(self), safe)
    end,
    method s-undefined(self, l): s-undefined(l) end,
    method s-srcloc(self, l, loc): s-srcloc(l, loc) end,
    method s-num(self, l, n): s-num(l, n) end,
    method s-frac(self, l, num, den): s-frac(l, num, den) end,
    method s-rfrac(self, l, num, den): s-rfrac(l, num, den) end,
    method s-bool(self, l, b): s-bool(l, b) end,
    method s-str(self, l, s): s-str(l, s) end,
    method s-dot(self, l, obj, field): s-dot(l, obj.visit(self), field) end,
    method s-get-bang(self, l, obj, field):
      s-get-bang(l, obj.visit(self), field)
    end,
    method s-bracket(self, l, obj, key):
      s-bracket(l, obj.visit(self), key.visit(self))
    end,
    method s-data(
        self,
        l,
        name,
        params,
        mixins,
        variants,
        shared-members,
        _check-loc,
        _check
      ):
      s-data(l,
        name,
        self.list(params),
        self.list(mixins),
        self.list(variants),
        self.list(shared-members),
        _check-loc,
        self.option(_check))
    end,
    method s-data-expr(
        self,
        l,
        name,
        namet,
        params,
        mixins,
        variants,
        shared-members,
        _check-loc,
        _check
      ):
      s-data-expr(l,
        name,
        namet.visit(self),
        self.list(params),
        self.list(mixins),
        self.list(variants),
        self.list(shared-members),
        _check-loc,
        self.option(_check))
    end,
    method s-for(self, l, iterator, bindings, ann, body, blocky):
      s-for(l,
        iterator.visit(self),
        self.list(bindings),
        ann.visit(self),
        body.visit(self),
        blocky)
    end,
    method s-check(self, l, name, body, keyword-check):
      s-check(l, name, body.visit(self), keyword-check)
    end,
    method s-reactor(self, l, fields): s-reactor(l, self.list(fields)) end,
    method s-table-extend(self, l, column-binds, extensions):
      s-table-extend(l, column-binds.visit(self), self.list(extensions))
    end,
    method s-table-update(self, l, column-binds, updates):
      s-table-update(l, column-binds.visit(self), self.list(updates))
    end,
    method s-table-select(self, l, columns, table):
      s-table-select(l, self.list(columns), table.visit(self))
    end,
    method s-table-order(self, l, table, ordering):
      s-table-order(l, table.visit(self), self.list(ordering))
    end,
    method s-table-filter(self, l, column-binds, predicate):
      s-table-filter(l, column-binds.visit(self), predicate.visit(self))
    end,
    method s-table-extract(self, l, column, table):
      s-table-extract(l, column.visit(self), table.visit(self))
    end,
    method s-table(self, l, headers, rows):
      s-table(l, self.list(headers), self.list(rows))
    end,
    method s-load-table(self, l, headers, spec):
      s-load-table(l, self.list(headers), self.list(spec))
    end,
    method s-spy-block(self, l, message, contents):
      s-spy-block(l, self.option(message), self.list(contents))
    end,
    method s-table-row(self, l, elems): s-table-row(l, self.list(elems)) end,
    method s-spy-name(self, l, name): s-spy-name(l, name.visit(self)) end,
    method s-spy-expr(self, l, name, value):
      s-spy-expr(l, name, value.visit(self))
    end,
    method s-construct-normal(self): s-construct-normal end,
    method s-construct-lazy(self): s-construct-lazy end,
    method s-bind(self, l, shadows, id, ann):
      s-bind(l, shadows, id.visit(self), ann.visit(self))
    end,
    method s-tuple-bind(self, l, fields, as-name):
      s-tuple-bind(l, self.list(fields), self.option(as-name))
    end,
    method s-data-field(self, l, name, value):
      s-data-field(l, name, value.visit(self))
    end,
    method s-mutable-field(self, l, name, ann, value):
      s-mutable-field(l, name, ann.visit(self), value.visit(self))
    end,
    method s-method-field(
        self,
        l,
        name,
        params,
        args,
        ann,
        doc,
        body,
        _check-loc,
        _check,
        blocky
      ):
      s-method-field(l,
        name,
        self.list(params),
        self.list(args),
        ann.visit(self),
        doc,
        body.visit(self),
        _check-loc,
        self.option(_check),
        blocky)
    end,
    method s-field-name(self, l, name, ann):
      s-field-name(l, name, ann.visit(self))
    end,
    method s-for-bind(self, l, bind, value):
      s-for-bind(l, bind.visit(self), value.visit(self))
    end,
    method s-column-binds(self, l, binds, table):
      s-column-binds(l, self.list(binds), table.visit(self))
    end,
    method ASCENDING(self): ASCENDING end,
    method DESCENDING(self): DESCENDING end,
    method s-column-sort(self, l, column, direction):
      s-column-sort(l, column.visit(self), direction.visit(self))
    end,
    method s-table-extend-field(self, l, name, value, ann):
      s-table-extend-field(l, name, value.visit(self), ann.visit(self))
    end,
    method s-table-extend-reducer(self, l, name, reducer, col, ann):
      s-table-extend-reducer(l,
        name,
        reducer.visit(self),
        col.visit(self),
        ann.visit(self))
    end,
    method s-sanitize(self, l, name, sanitizer):
      s-sanitize(l, name.visit(self), sanitizer.visit(self))
    end,
    method s-table-src(self, l, src): s-table-src(l, src.visit(self)) end,
    method s-normal(self): s-normal end,
    method s-mutable(self): s-mutable end,
    method s-variant-member(self, l, member-type, bind):
      s-variant-member(l, member-type.visit(self), bind.visit(self))
    end,
    method s-variant(self, l, constr-loc, name, members, with-members):
      s-variant(l,
        constr-loc,
        name,
        self.list(members),
        self.list(with-members))
    end,
    method s-singleton-variant(self, l, name, with-members):
      s-singleton-variant(l, name, self.list(with-members))
    end,
    method s-if-branch(self, l, test, body):
      s-if-branch(l, test.visit(self), body.visit(self))
    end,
    method s-if-pipe-branch(self, l, test, body):
      s-if-pipe-branch(l, test.visit(self), body.visit(self))
    end,
    method s-cases-bind-ref(self): s-cases-bind-ref end,
    method s-cases-bind-normal(self): s-cases-bind-normal end,
    method s-cases-bind(self, l, field-type, bind):
      s-cases-bind(l, field-type.visit(self), bind.visit(self))
    end,
    method s-cases-branch(self, l, pat-loc, name, args, body):
      s-cases-branch(l, pat-loc, name, self.list(args), body.visit(self))
    end,
    method s-singleton-cases-branch(self, l, pat-loc, name, body):
      s-singleton-cases-branch(l, pat-loc, name, body.visit(self))
    end,
    method s-op-is(self, l): s-op-is(l) end,
    method s-op-is-roughly(self, l): s-op-is-roughly(l) end,
    method s-op-is-op(self, l, op): s-op-is-op(l, op) end,
    method s-op-is-not(self, l): s-op-is-not(l) end,
    method s-op-is-not-op(self, l, op): s-op-is-not-op(l, op) end,
    method s-op-satisfies(self, l): s-op-satisfies(l) end,
    method s-op-satisfies-not(self, l): s-op-satisfies-not(l) end,
    method s-op-raises(self, l): s-op-raises(l) end,
    method s-op-raises-other(self, l): s-op-raises-other(l) end,
    method s-op-raises-not(self, l): s-op-raises-not(l) end,
    method s-op-raises-satisfies(self, l): s-op-raises-satisfies(l) end,
    method s-op-raises-violates(self, l): s-op-raises-violates(l) end,
    method a-blank(self): a-blank end,
    method a-any(self, l): a-any(l) end,
    method a-name(self, l, id): a-name(l, id.visit(self)) end,
    method a-type-var(self, l, id): a-type-var(l, id.visit(self)) end,
    method a-arrow(self, l, args, ret, use-parens):
      a-arrow(l, self.list(args), ret.visit(self), use-parens)
    end,
    method a-arrow-argnames(self, l, args, ret, use-parens):
      a-arrow-argnames(l, self.list(args), ret.visit(self), use-parens)
    end,
    method a-method(self, l, args, ret):
      a-method(l, self.list(args), ret.visit(self))
    end,
    method a-record(self, l, fields): a-record(l, self.list(fields)) end,
    method a-tuple(self, l, fields): a-tuple(l, self.list(fields)) end,
    method a-app(self, l, ann, args):
      a-app(l, ann.visit(self), self.list(args))
    end,
    method a-pred(self, l, ann, exp):
      a-pred(l, ann.visit(self), exp.visit(self))
    end,
    method a-dot(self, l, obj, field): a-dot(l, obj.visit(self), field) end,
    method a-checked(self, checked, residual):
      a-checked(checked.visit(self), residual.visit(self))
    end,
    method a-field(self, l, name, ann): a-field(l, name, ann.visit(self)) end
  }
shadow dummy-loc-visitor =
  {
    method option(self, opt):
      cases(Option) opt: | none => none | some( v) => some(v.visit(self)) end
    end,
    method list(self, lst):
      cases(List) lst:
        | empty => empty
        | link( f,  r) => link(f.visit(self), self.list(r))
      end
    end,
    method s-underscore(self, l): s-underscore(dummy-loc) end,
    method s-name(self, l, s): s-name(dummy-loc, s) end,
    method s-global(self, s): s-global(s) end,
    method s-type-global(self, s): s-type-global(s) end,
    method s-atom(self, base, serial): s-atom(base, serial) end,
    method app-info-c(self, is-recursive, is-tail):
      app-info-c(is-recursive, is-tail)
    end,
    method s-program(self, l, _provide, provided-types, imports, block):
      s-program(dummy-loc,
        _provide.visit(self),
        provided-types.visit(self),
        self.list(imports),
        block.visit(self))
    end,
    method s-include(self, l, mod): s-include(dummy-loc, mod.visit(self)) end,
    method s-import(self, l, file, name):
      s-import(dummy-loc, file.visit(self), name.visit(self))
    end,
    method s-import-types(self, l, file, name, types):
      s-import-types(dummy-loc,
        file.visit(self),
        name.visit(self),
        types.visit(self))
    end,
    method s-import-fields(self, l, fields, file):
      s-import-fields(dummy-loc, self.list(fields), file.visit(self))
    end,
    method s-import-complete(
        self,
        l,
        values,
        types,
        import-type,
        vals-name,
        types-name
      ):
      s-import-complete(dummy-loc,
        self.list(values),
        self.list(types),
        import-type.visit(self),
        vals-name.visit(self),
        types-name.visit(self))
    end,
    method p-value(self, l, v, ann):
      p-value(dummy-loc, v.visit(self), ann.visit(self))
    end,
    method p-alias(self, l, in-name, out-name, mod):
      p-alias(dummy-loc,
        in-name.visit(self),
        out-name.visit(self),
        self.option(mod))
    end,
    method p-data(self, l, d, mod):
      p-data(dummy-loc, d.visit(self), self.option(mod))
    end,
    method s-provide(self, l, block):
      s-provide(dummy-loc, block.visit(self))
    end,
    method s-provide-complete(self, l, values, aliases, data-definitions):
      s-provide-complete(dummy-loc,
        self.list(values),
        self.list(aliases),
        self.list(data-definitions))
    end,
    method s-provide-all(self, l): s-provide-all(dummy-loc) end,
    method s-provide-none(self, l): s-provide-none(dummy-loc) end,
    method s-provide-types(self, l, ann):
      s-provide-types(dummy-loc, self.list(ann))
    end,
    method s-provide-types-all(self, l): s-provide-types-all(dummy-loc) end,
    method s-provide-types-none(self, l): s-provide-types-none(dummy-loc) end,
    method s-const-import(self, l, mod): s-const-import(dummy-loc, mod) end,
    method s-special-import(self, l, kind, args):
      s-special-import(dummy-loc, kind, args)
    end,
    method h-use-loc(self, l): h-use-loc(dummy-loc) end,
    method s-let-bind(self, l, b, value):
      s-let-bind(dummy-loc, b.visit(self), value.visit(self))
    end,
    method s-var-bind(self, l, b, value):
      s-var-bind(dummy-loc, b.visit(self), value.visit(self))
    end,
    method s-letrec-bind(self, l, b, value):
      s-letrec-bind(dummy-loc, b.visit(self), value.visit(self))
    end,
    method s-type-bind(self, l, name, params, ann):
      s-type-bind(dummy-loc,
        name.visit(self),
        self.list(params),
        ann.visit(self))
    end,
    method s-newtype-bind(self, l, name, namet):
      s-newtype-bind(dummy-loc, name.visit(self), namet.visit(self))
    end,
    method s-defined-value(self, name, value):
      s-defined-value(name, value.visit(self))
    end,
    method s-defined-var(self, name, id):
      s-defined-var(name, id.visit(self))
    end,
    method s-defined-type(self, name, typ):
      s-defined-type(name, typ.visit(self))
    end,
    method s-module(
        self,
        l,
        answer,
        defined-values,
        defined-types,
        provided-values,
        provided-types,
        checks
      ):
      s-module(dummy-loc,
        answer.visit(self),
        self.list(defined-values),
        self.list(defined-types),
        provided-values.visit(self),
        self.list(provided-types),
        checks.visit(self))
    end,
    method s-template(self, l): s-template(dummy-loc) end,
    method s-type-let-expr(self, l, binds, body, blocky):
      s-type-let-expr(dummy-loc, self.list(binds), body.visit(self), blocky)
    end,
    method s-let-expr(self, l, binds, body, blocky):
      s-let-expr(dummy-loc, self.list(binds), body.visit(self), blocky)
    end,
    method s-letrec(self, l, binds, body, blocky):
      s-letrec(dummy-loc, self.list(binds), body.visit(self), blocky)
    end,
    method s-hint-exp(self, l, hints, exp):
      s-hint-exp(dummy-loc, self.list(hints), exp.visit(self))
    end,
    method s-instantiate(self, l, expr, params):
      s-instantiate(dummy-loc, expr.visit(self), self.list(params))
    end,
    method s-block(self, l, stmts): s-block(dummy-loc, self.list(stmts)) end,
    method s-user-block(self, l, body):
      s-user-block(dummy-loc, body.visit(self))
    end,
    method s-fun(
        self,
        l,
        name,
        params,
        args,
        ann,
        doc,
        body,
        _check-loc,
        _check,
        blocky
      ):
      s-fun(dummy-loc,
        name,
        self.list(params),
        self.list(args),
        ann.visit(self),
        doc,
        body.visit(self),
        _check-loc,
        self.option(_check),
        blocky)
    end,
    method s-type(self, l, name, params, ann):
      s-type(dummy-loc, name.visit(self), self.list(params), ann.visit(self))
    end,
    method s-newtype(self, l, name, namet):
      s-newtype(dummy-loc, name.visit(self), namet.visit(self))
    end,
    method s-var(self, l, name, value):
      s-var(dummy-loc, name.visit(self), value.visit(self))
    end,
    method s-rec(self, l, name, value):
      s-rec(dummy-loc, name.visit(self), value.visit(self))
    end,
    method s-let(self, l, name, value, keyword-val):
      s-let(dummy-loc, name.visit(self), value.visit(self), keyword-val)
    end,
    method s-ref(self, l, ann): s-ref(dummy-loc, self.option(ann)) end,
    method s-contract(self, l, name, ann):
      s-contract(dummy-loc, name.visit(self), ann.visit(self))
    end,
    method s-when(self, l, test, block, blocky):
      s-when(dummy-loc, test.visit(self), block.visit(self), blocky)
    end,
    method s-assign(self, l, id, value):
      s-assign(dummy-loc, id.visit(self), value.visit(self))
    end,
    method s-if-pipe(self, l, branches, blocky):
      s-if-pipe(dummy-loc, self.list(branches), blocky)
    end,
    method s-if-pipe-else(self, l, branches, _else, blocky):
      s-if-pipe-else(dummy-loc, self.list(branches), _else.visit(self), blocky)
    end,
    method s-if(self, l, branches, blocky):
      s-if(dummy-loc, self.list(branches), blocky)
    end,
    method s-if-else(self, l, branches, _else, blocky):
      s-if-else(dummy-loc, self.list(branches), _else.visit(self), blocky)
    end,
    method s-cases(self, l, typ, val, branches, blocky):
      s-cases(dummy-loc,
        typ.visit(self),
        val.visit(self),
        self.list(branches),
        blocky)
    end,
    method s-cases-else(self, l, typ, val, branches, _else, blocky):
      s-cases-else(dummy-loc,
        typ.visit(self),
        val.visit(self),
        self.list(branches),
        _else.visit(self),
        blocky)
    end,
    method s-op(self, l, op-l, op, left, right):
      s-op(dummy-loc, dummy-loc, op, left.visit(self), right.visit(self))
    end,
    method s-check-test(self, l, op, refinement, left, right):
      s-check-test(dummy-loc,
        op.visit(self),
        self.option(refinement),
        left.visit(self),
        self.option(right))
    end,
    method s-check-expr(self, l, expr, ann):
      s-check-expr(dummy-loc, expr.visit(self), ann.visit(self))
    end,
    method s-paren(self, l, expr): s-paren(dummy-loc, expr.visit(self)) end,
    method s-lam(
        self,
        l,
        name,
        params,
        args,
        ann,
        doc,
        body,
        _check-loc,
        _check,
        blocky
      ):
      s-lam(dummy-loc,
        "",
        self.list(params),
        self.list(args),
        ann.visit(self),
        doc,
        body.visit(self),
        _check-loc,
        self.option(_check),
        blocky)
    end,
    method s-method(
        self,
        l,
        name,
        params,
        args,
        ann,
        doc,
        body,
        _check-loc,
        _check,
        blocky
      ):
      s-method(dummy-loc,
        name,
        self.list(params),
        self.list(args),
        ann.visit(self),
        doc,
        body.visit(self),
        _check-loc,
        self.option(_check),
        blocky)
    end,
    method s-extend(self, l, supe, fields):
      s-extend(dummy-loc, supe.visit(self), self.list(fields))
    end,
    method s-update(self, l, supe, fields):
      s-update(dummy-loc, supe.visit(self), self.list(fields))
    end,
    method s-tuple(self, l, fields): s-tuple(dummy-loc, self.list(fields)) end,
    method s-tuple-get(self, l, tup, index, index-loc):
      s-tuple-get(dummy-loc, tup.visit(self), index, dummy-loc)
    end,
    method s-obj(self, l, fields): s-obj(dummy-loc, self.list(fields)) end,
    method s-array(self, l, values): s-array(dummy-loc, self.list(values)) end,
    method s-construct(self, l, modifier, constructor, values):
      s-construct(dummy-loc,
        modifier.visit(self),
        constructor.visit(self),
        self.list(values))
    end,
    method s-app(self, l, _fun, args):
      s-app(dummy-loc, _fun.visit(self), self.list(args))
    end,
    method s-app-enriched(self, l, _fun, args, app-info):
      s-app-enriched(dummy-loc,
        _fun.visit(self),
        self.list(args),
        app-info.visit(self))
    end,
    method s-prim-app(self, l, _fun, args):
      s-prim-app(dummy-loc, _fun, self.list(args))
    end,
    method s-prim-val(self, l, name): s-prim-val(dummy-loc, name) end,
    method s-id(self, l, id): s-id(dummy-loc, id.visit(self)) end,
    method s-id-var(self, l, id): s-id-var(dummy-loc, id.visit(self)) end,
    method s-id-letrec(self, l, id, safe):
      s-id-letrec(dummy-loc, id.visit(self), safe)
    end,
    method s-undefined(self, l): s-undefined(dummy-loc) end,
    method s-srcloc(self, l, loc): s-srcloc(dummy-loc, dummy-loc) end,
    method s-num(self, l, n): s-num(dummy-loc, n) end,
    method s-frac(self, l, num, den): s-frac(dummy-loc, num, den) end,
    method s-rfrac(self, l, num, den): s-rfrac(dummy-loc, num, den) end,
    method s-bool(self, l, b): s-bool(dummy-loc, b) end,
    method s-str(self, l, s): s-str(dummy-loc, s) end,
    method s-dot(self, l, obj, field):
      s-dot(dummy-loc, obj.visit(self), field)
    end,
    method s-get-bang(self, l, obj, field):
      s-get-bang(dummy-loc, obj.visit(self), field)
    end,
    method s-bracket(self, l, obj, key):
      s-bracket(dummy-loc, obj.visit(self), key.visit(self))
    end,
    method s-data(
        self,
        l,
        name,
        params,
        mixins,
        variants,
        shared-members,
        _check-loc,
        _check
      ):
      s-data(dummy-loc,
        name,
        self.list(params),
        self.list(mixins),
        self.list(variants),
        self.list(shared-members),
        _check-loc,
        self.option(_check))
    end,
    method s-data-expr(
        self,
        l,
        name,
        namet,
        params,
        mixins,
        variants,
        shared-members,
        _check-loc,
        _check
      ):
      s-data-expr(dummy-loc,
        name,
        namet.visit(self),
        self.list(params),
        self.list(mixins),
        self.list(variants),
        self.list(shared-members),
        _check-loc,
        self.option(_check))
    end,
    method s-for(self, l, iterator, bindings, ann, body, blocky):
      s-for(dummy-loc,
        iterator.visit(self),
        self.list(bindings),
        ann.visit(self),
        body.visit(self),
        blocky)
    end,
    method s-check(self, l, name, body, keyword-check):
      s-check(dummy-loc, name, body.visit(self), keyword-check)
    end,
    method s-reactor(self, l, fields):
      s-reactor(dummy-loc, self.list(fields))
    end,
    method s-table-extend(self, l, column-binds, extensions):
      s-table-extend(dummy-loc, column-binds.visit(self), self.list(extensions))
    end,
    method s-table-update(self, l, column-binds, updates):
      s-table-update(dummy-loc, column-binds.visit(self), self.list(updates))
    end,
    method s-table-select(self, l, columns, table):
      s-table-select(dummy-loc, self.list(columns), table.visit(self))
    end,
    method s-table-order(self, l, table, ordering):
      s-table-order(dummy-loc, table.visit(self), self.list(ordering))
    end,
    method s-table-filter(self, l, column-binds, predicate):
      s-table-filter(dummy-loc, column-binds.visit(self), predicate.visit(self))
    end,
    method s-table-extract(self, l, column, table):
      s-table-extract(dummy-loc, column.visit(self), table.visit(self))
    end,
    method s-table(self, l, headers, rows):
      s-table(dummy-loc, self.list(headers), self.list(rows))
    end,
    method s-load-table(self, l, headers, spec):
      s-load-table(dummy-loc, self.list(headers), self.list(spec))
    end,
    method s-spy-block(self, l, message, contents):
      s-spy-block(dummy-loc, self.option(message), self.list(contents))
    end,
    method s-table-row(self, l, elems):
      s-table-row(dummy-loc, self.list(elems))
    end,
    method s-spy-name(self, l, name):
      s-spy-name(dummy-loc, name.visit(self))
    end,
    method s-spy-expr(self, l, name, value):
      s-spy-expr(dummy-loc, name, value.visit(self))
    end,
    method s-construct-normal(self): s-construct-normal end,
    method s-construct-lazy(self): s-construct-lazy end,
    method s-bind(self, l, shadows, id, ann):
      s-bind(dummy-loc, shadows, id.visit(self), ann.visit(self))
    end,
    method s-tuple-bind(self, l, fields, as-name):
      s-tuple-bind(dummy-loc, self.list(fields), self.option(as-name))
    end,
    method s-data-field(self, l, name, value):
      s-data-field(dummy-loc, name, value.visit(self))
    end,
    method s-mutable-field(self, l, name, ann, value):
      s-mutable-field(dummy-loc, name, ann.visit(self), value.visit(self))
    end,
    method s-method-field(
        self,
        l,
        name,
        params,
        args,
        ann,
        doc,
        body,
        _check-loc,
        _check,
        blocky
      ):
      s-method-field(dummy-loc,
        name,
        self.list(params),
        self.list(args),
        ann.visit(self),
        doc,
        body.visit(self),
        _check-loc,
        self.option(_check),
        blocky)
    end,
    method s-field-name(self, l, name, ann):
      s-field-name(dummy-loc, name, ann.visit(self))
    end,
    method s-for-bind(self, l, bind, value):
      s-for-bind(dummy-loc, bind.visit(self), value.visit(self))
    end,
    method s-column-binds(self, l, binds, table):
      s-column-binds(dummy-loc, self.list(binds), table.visit(self))
    end,
    method ASCENDING(self): ASCENDING end,
    method DESCENDING(self): DESCENDING end,
    method s-column-sort(self, l, column, direction):
      s-column-sort(dummy-loc, column.visit(self), direction.visit(self))
    end,
    method s-table-extend-field(self, l, name, value, ann):
      s-table-extend-field(dummy-loc, name, value.visit(self), ann.visit(self))
    end,
    method s-table-extend-reducer(self, l, name, reducer, col, ann):
      s-table-extend-reducer(dummy-loc,
        name,
        reducer.visit(self),
        col.visit(self),
        ann.visit(self))
    end,
    method s-sanitize(self, l, name, sanitizer):
      s-sanitize(dummy-loc, name.visit(self), sanitizer.visit(self))
    end,
    method s-table-src(self, l, src):
      s-table-src(dummy-loc, src.visit(self))
    end,
    method s-normal(self): s-normal end,
    method s-mutable(self): s-mutable end,
    method s-variant-member(self, l, member-type, bind):
      s-variant-member(dummy-loc, member-type.visit(self), bind.visit(self))
    end,
    method s-variant(self, l, constr-loc, name, members, with-members):
      s-variant(dummy-loc,
        dummy-loc,
        name,
        self.list(members),
        self.list(with-members))
    end,
    method s-singleton-variant(self, l, name, with-members):
      s-singleton-variant(dummy-loc, name, self.list(with-members))
    end,
    method s-if-branch(self, l, test, body):
      s-if-branch(dummy-loc, test.visit(self), body.visit(self))
    end,
    method s-if-pipe-branch(self, l, test, body):
      s-if-pipe-branch(dummy-loc, test.visit(self), body.visit(self))
    end,
    method s-cases-bind-ref(self): s-cases-bind-ref end,
    method s-cases-bind-normal(self): s-cases-bind-normal end,
    method s-cases-bind(self, l, field-type, bind):
      s-cases-bind(dummy-loc, field-type.visit(self), bind.visit(self))
    end,
    method s-cases-branch(self, l, pat-loc, name, args, body):
      s-cases-branch(dummy-loc,
        dummy-loc,
        name,
        self.list(args),
        body.visit(self))
    end,
    method s-singleton-cases-branch(self, l, pat-loc, name, body):
      s-singleton-cases-branch(dummy-loc, dummy-loc, name, body.visit(self))
    end,
    method s-op-is(self, l): s-op-is(dummy-loc) end,
    method s-op-is-roughly(self, l): s-op-is-roughly(dummy-loc) end,
    method s-op-is-op(self, l, op): s-op-is-op(dummy-loc, op) end,
    method s-op-is-not(self, l): s-op-is-not(dummy-loc) end,
    method s-op-is-not-op(self, l, op): s-op-is-not-op(dummy-loc, op) end,
    method s-op-satisfies(self, l): s-op-satisfies(dummy-loc) end,
    method s-op-satisfies-not(self, l): s-op-satisfies-not(dummy-loc) end,
    method s-op-raises(self, l): s-op-raises(dummy-loc) end,
    method s-op-raises-other(self, l): s-op-raises-other(dummy-loc) end,
    method s-op-raises-not(self, l): s-op-raises-not(dummy-loc) end,
    method s-op-raises-satisfies(self, l): s-op-raises-satisfies(dummy-loc) end,
    method s-op-raises-violates(self, l): s-op-raises-violates(dummy-loc) end,
    method a-blank(self): a-blank end,
    method a-any(self, l): a-any(dummy-loc) end,
    method a-name(self, l, id): a-name(dummy-loc, id.visit(self)) end,
    method a-type-var(self, l, id): a-type-var(dummy-loc, id.visit(self)) end,
    method a-arrow(self, l, args, ret, use-parens):
      a-arrow(dummy-loc, self.list(args), ret.visit(self), use-parens)
    end,
    method a-arrow-argnames(self, l, args, ret, use-parens):
      a-arrow-argnames(dummy-loc, self.list(args), ret.visit(self), use-parens)
    end,
    method a-method(self, l, args, ret):
      a-method(dummy-loc, self.list(args), ret.visit(self))
    end,
    method a-record(self, l, fields): a-record(dummy-loc, self.list(fields)) end,
    method a-tuple(self, l, fields): a-tuple(dummy-loc, self.list(fields)) end,
    method a-app(self, l, ann, args):
      a-app(dummy-loc, ann.visit(self), self.list(args))
    end,
    method a-pred(self, l, ann, exp):
      a-pred(dummy-loc, ann.visit(self), exp.visit(self))
    end,
    method a-dot(self, l, obj, field):
      a-dot(dummy-loc, obj.visit(self), field)
    end,
    method a-checked(self, checked, residual):
      a-checked(checked.visit(self), residual.visit(self))
    end,
    method a-field(self, l, name, ann):
      a-field(dummy-loc, name, ann.visit(self))
    end
  }