(function () {
function id(x) { return x[0]; }

const R = require('requirejs');

R.config({paths: {'jglr': '../jglr', 'nearley': '.'}});

const T = R('nearley/nearley-tokenizer');
const tokenizer = T.Tokenizer;
const E = R('jglr/jglr');
const SrcLoc = E.SrcLoc;

const toString = function(show_pos) {
  var toStr = "(" + this.name;
  if (show_pos)
    toStr += "@" + this.pos.toString(true);
  for (var i = 0; i < this.kids.length; i++) {
    if (this.kids[i].toRepr)
      toStr += " " + this.kids[i].toRepr(true);
    else if (this.kids[i].asString)
      toStr += " " + this.kids[i].asString
    else
      toStr += " " + this.kids[i].toString(true);
  }
  toStr += ")";
  return toStr;
};

const defaultAction = function (name) {
  const ret = function (kids) {
    var useful_kids = [];
    for (var i = 0; i < kids.length; i++) {
      if (kids[i].shouldInline === true) useful_kids = useful_kids.concat(kids[i].kids);
      else useful_kids.push(kids[i]);
    }
    if (useful_kids.length > 0) {
      const pos = useful_kids[0].pos.combine(useful_kids[useful_kids.length  - 1].pos);
      return { name, kids: useful_kids, toString, pos };
    } else if (tokenizer.pos !== undefined && tokenizer.curCol !== undefined && tokenizer.curLine !== undefined) {
      const pos = SrcLoc.make(tokenizer.curLine, tokenizer.curCol, tokenizer.pos, tokenizer.curLine, tokenizer.curCol, tokenizer.pos);
      return { name, kids: useful_kids, toString, pos };
    } else {
      const pos = SrcLoc.make(1, 0, 0, 1, 0, 0);
      return { name, kids: useful_kids, toString, pos };
    }
  }
  return ret;
};

const inlineAction = function (name) {
  const ret = function (kids) {
    const defaultRet = defaultAction(name)(kids);
    defaultRet.shouldInline = true;
    return defaultRet;
  }
  return ret;
};

const listSnocAction = function(tail, head, shouldInline) {
  const ret = function (kids) {
    const name = tail;
    var useful_kids = [];
    for (var i = 0; i < kids.length; i++) {
      if (kids[i].name === head) {
        if (kids[i].shouldInline === true)
          useful_kids = useful_kids.concat(kids[i].kids);
        else
          useful_kids.push(kids[i]);
      } else if (kids[i].name === tail) useful_kids = useful_kids.concat(kids[i].kids); 
    }
    if (useful_kids.length > 0) {
      const pos = useful_kids[0].pos.combine(useful_kids[useful_kids.length  - 1].pos);
      return { name, kids: useful_kids, toString, pos, shouldInline };
    } else if (tokenizer.pos !== undefined && tokenizer.curCol !== undefined && tokenizer.curLine !== undefined) {
      const pos = SrcLoc.make(tokenizer.curLine, tokenizer.curCol, tokenizer.pos, tokenizer.curLine, tokenizer.curCol, tokenizer.pos);
      return { name, kids: useful_kids, toString, pos, shouldInline };
    } else {
      const pos = SrcLoc.make(1, 0, 0, 1, 0, 0);
      return { name, kids: useful_kids, toString, pos, shouldInline };
    }
  }
  return ret;
};

var grammar = {
	Lexer: tokenizer,
  ParserRules: [
  {"name": "program", "symbols": ["prelude", "block"], "postprocess": defaultAction("program")},
  {"name": "prelude", "symbols": ["prelude_I0*"], "postprocess": defaultAction("prelude")},
  {"name": "prelude_I0*", "symbols": [], "postprocess": inlineAction("prelude_I0*")},
  {"name": "prelude_I0*", "symbols": ["prelude_I0*", "prelude_I0"], "postprocess": listSnocAction("prelude_I0*", "prelude_I0", true)},
  {"name": "prelude_I0", "symbols": ["provide-stmt"], "postprocess": inlineAction("prelude_I0")},
  {"name": "prelude_I0", "symbols": ["import-stmt"], "postprocess": inlineAction("prelude_I0")},
  {"name": "import-stmt", "symbols": [(tokenizer.has("INCLUDE") ? {type: "INCLUDE"} : "INCLUDE"), "import-source"], "postprocess": defaultAction("import-stmt")},
  {"name": "import-stmt", "symbols": [(tokenizer.has("INCLUDE") ? {type: "INCLUDE"} : "INCLUDE"), (tokenizer.has("FROM") ? {type: "FROM"} : "FROM"), "module-ref", (tokenizer.has("COLON") ? {type: "COLON"} : "COLON"), "import-stmt_A1_I4?", (tokenizer.has("END") ? {type: "END"} : "END")], "postprocess": defaultAction("import-stmt")},
  {"name": "import-stmt_A1_I4?", "symbols": [], "postprocess": inlineAction("import-stmt_A1_I4?")},
  {"name": "import-stmt_A1_I4?", "symbols": ["import-stmt_A1_I4"], "postprocess": inlineAction("import-stmt_A1_I4?")},
  {"name": "import-stmt_A1_I4", "symbols": ["include-spec", "import-stmt_A1_I4_I1*", "import-stmt_A1_I4_I2?"], "postprocess": inlineAction("import-stmt_A1_I4")},
  {"name": "import-stmt_A1_I4_I1*", "symbols": [], "postprocess": inlineAction("import-stmt_A1_I4_I1*")},
  {"name": "import-stmt_A1_I4_I1*", "symbols": ["import-stmt_A1_I4_I1*", "import-stmt_A1_I4_I1"], "postprocess": listSnocAction("import-stmt_A1_I4_I1*", "import-stmt_A1_I4_I1", true)},
  {"name": "import-stmt_A1_I4_I1", "symbols": [(tokenizer.has("COMMA") ? {type: "COMMA"} : "COMMA"), "include-spec"], "postprocess": inlineAction("import-stmt_A1_I4_I1")},
  {"name": "import-stmt_A1_I4_I2?", "symbols": [], "postprocess": inlineAction("import-stmt_A1_I4_I2?")},
  {"name": "import-stmt_A1_I4_I2?", "symbols": ["import-stmt_A1_I4_I2"], "postprocess": inlineAction("import-stmt_A1_I4_I2?")},
  {"name": "import-stmt_A1_I4_I2", "symbols": [(tokenizer.has("COMMA") ? {type: "COMMA"} : "COMMA")], "postprocess": inlineAction("import-stmt_A1_I4_I2")},
  {"name": "import-stmt", "symbols": [(tokenizer.has("IMPORT") ? {type: "IMPORT"} : "IMPORT"), "import-source", (tokenizer.has("AS") ? {type: "AS"} : "AS"), (tokenizer.has("NAME") ? {type: "NAME"} : "NAME")], "postprocess": defaultAction("import-stmt")},
  {"name": "import-stmt", "symbols": [(tokenizer.has("IMPORT") ? {type: "IMPORT"} : "IMPORT"), "comma-names", (tokenizer.has("FROM") ? {type: "FROM"} : "FROM"), "import-source"], "postprocess": defaultAction("import-stmt")},
  {"name": "import-source", "symbols": ["import-special"], "postprocess": defaultAction("import-source")},
  {"name": "import-source", "symbols": ["import-name"], "postprocess": defaultAction("import-source")},
  {"name": "import-special", "symbols": [(tokenizer.has("NAME") ? {type: "NAME"} : "NAME"), (tokenizer.has("PARENNOSPACE") ? {type: "PARENNOSPACE"} : "PARENNOSPACE"), (tokenizer.has("STRING") ? {type: "STRING"} : "STRING"), "import-special_I3*", (tokenizer.has("RPAREN") ? {type: "RPAREN"} : "RPAREN")], "postprocess": defaultAction("import-special")},
  {"name": "import-special_I3*", "symbols": [], "postprocess": inlineAction("import-special_I3*")},
  {"name": "import-special_I3*", "symbols": ["import-special_I3*", "import-special_I3"], "postprocess": listSnocAction("import-special_I3*", "import-special_I3", true)},
  {"name": "import-special_I3", "symbols": [(tokenizer.has("COMMA") ? {type: "COMMA"} : "COMMA"), (tokenizer.has("STRING") ? {type: "STRING"} : "STRING")], "postprocess": inlineAction("import-special_I3")},
  {"name": "import-name", "symbols": [(tokenizer.has("NAME") ? {type: "NAME"} : "NAME")], "postprocess": defaultAction("import-name")},
  {"name": "include-spec", "symbols": ["include-name-spec"], "postprocess": defaultAction("include-spec")},
  {"name": "include-spec", "symbols": ["include-type-spec"], "postprocess": defaultAction("include-spec")},
  {"name": "include-spec", "symbols": ["include-data-spec"], "postprocess": defaultAction("include-spec")},
  {"name": "include-spec", "symbols": ["include-module-spec"], "postprocess": defaultAction("include-spec")},
  {"name": "include-name-spec", "symbols": ["name-spec"], "postprocess": defaultAction("include-name-spec")},
  {"name": "include-type-spec", "symbols": [(tokenizer.has("TYPE") ? {type: "TYPE"} : "TYPE"), "name-spec"], "postprocess": defaultAction("include-type-spec")},
  {"name": "include-data-spec", "symbols": [(tokenizer.has("DATA") ? {type: "DATA"} : "DATA"), "data-name-spec", "include-data-spec_I2?"], "postprocess": defaultAction("include-data-spec")},
  {"name": "include-data-spec_I2?", "symbols": [], "postprocess": inlineAction("include-data-spec_I2?")},
  {"name": "include-data-spec_I2?", "symbols": ["include-data-spec_I2"], "postprocess": inlineAction("include-data-spec_I2?")},
  {"name": "include-data-spec_I2", "symbols": ["hiding-spec"], "postprocess": inlineAction("include-data-spec_I2")},
  {"name": "include-module-spec", "symbols": [(tokenizer.has("MODULE") ? {type: "MODULE"} : "MODULE"), "name-spec"], "postprocess": defaultAction("include-module-spec")},
  {"name": "provide-stmt", "symbols": ["provide-vals-stmt"], "postprocess": defaultAction("provide-stmt")},
  {"name": "provide-stmt", "symbols": ["provide-types-stmt"], "postprocess": defaultAction("provide-stmt")},
  {"name": "provide-stmt", "symbols": ["provide-block"], "postprocess": defaultAction("provide-stmt")},
  {"name": "provide-vals-stmt", "symbols": [(tokenizer.has("PROVIDE") ? {type: "PROVIDE"} : "PROVIDE"), "stmt", (tokenizer.has("END") ? {type: "END"} : "END")], "postprocess": defaultAction("provide-vals-stmt")},
  {"name": "provide-vals-stmt", "symbols": [(tokenizer.has("PROVIDE") ? {type: "PROVIDE"} : "PROVIDE"), "provide-vals-stmt_A1_I1"], "postprocess": defaultAction("provide-vals-stmt")},
  {"name": "provide-vals-stmt_A1_I1", "symbols": [(tokenizer.has("STAR") ? {type: "STAR"} : "STAR")], "postprocess": inlineAction("provide-vals-stmt_A1_I1")},
  {"name": "provide-vals-stmt_A1_I1", "symbols": [(tokenizer.has("TIMES") ? {type: "TIMES"} : "TIMES")], "postprocess": inlineAction("provide-vals-stmt_A1_I1")},
  {"name": "provide-types-stmt", "symbols": [(tokenizer.has("PROVIDE-TYPES") ? {type: "PROVIDE-TYPES"} : "PROVIDE-TYPES"), "record-ann"], "postprocess": defaultAction("provide-types-stmt")},
  {"name": "provide-types-stmt", "symbols": [(tokenizer.has("PROVIDE-TYPES") ? {type: "PROVIDE-TYPES"} : "PROVIDE-TYPES"), "provide-types-stmt_A1_I1"], "postprocess": defaultAction("provide-types-stmt")},
  {"name": "provide-types-stmt_A1_I1", "symbols": [(tokenizer.has("STAR") ? {type: "STAR"} : "STAR")], "postprocess": inlineAction("provide-types-stmt_A1_I1")},
  {"name": "provide-types-stmt_A1_I1", "symbols": [(tokenizer.has("TIMES") ? {type: "TIMES"} : "TIMES")], "postprocess": inlineAction("provide-types-stmt_A1_I1")},
  {"name": "provide-block", "symbols": [(tokenizer.has("PROVIDECOLON") ? {type: "PROVIDECOLON"} : "PROVIDECOLON"), "provide-block_A0_I1?", (tokenizer.has("END") ? {type: "END"} : "END")], "postprocess": defaultAction("provide-block")},
  {"name": "provide-block_A0_I1?", "symbols": [], "postprocess": inlineAction("provide-block_A0_I1?")},
  {"name": "provide-block_A0_I1?", "symbols": ["provide-block_A0_I1"], "postprocess": inlineAction("provide-block_A0_I1?")},
  {"name": "provide-block_A0_I1", "symbols": ["provide-spec", "provide-block_A0_I1_I1*", "provide-block_A0_I1_I2?"], "postprocess": inlineAction("provide-block_A0_I1")},
  {"name": "provide-block_A0_I1_I1*", "symbols": [], "postprocess": inlineAction("provide-block_A0_I1_I1*")},
  {"name": "provide-block_A0_I1_I1*", "symbols": ["provide-block_A0_I1_I1*", "provide-block_A0_I1_I1"], "postprocess": listSnocAction("provide-block_A0_I1_I1*", "provide-block_A0_I1_I1", true)},
  {"name": "provide-block_A0_I1_I1", "symbols": [(tokenizer.has("COMMA") ? {type: "COMMA"} : "COMMA"), "provide-spec"], "postprocess": inlineAction("provide-block_A0_I1_I1")},
  {"name": "provide-block_A0_I1_I2?", "symbols": [], "postprocess": inlineAction("provide-block_A0_I1_I2?")},
  {"name": "provide-block_A0_I1_I2?", "symbols": ["provide-block_A0_I1_I2"], "postprocess": inlineAction("provide-block_A0_I1_I2?")},
  {"name": "provide-block_A0_I1_I2", "symbols": [(tokenizer.has("COMMA") ? {type: "COMMA"} : "COMMA")], "postprocess": inlineAction("provide-block_A0_I1_I2")},
  {"name": "provide-block", "symbols": [(tokenizer.has("PROVIDE") ? {type: "PROVIDE"} : "PROVIDE"), (tokenizer.has("FROM") ? {type: "FROM"} : "FROM"), "module-ref", (tokenizer.has("COLON") ? {type: "COLON"} : "COLON"), "provide-block_A1_I4?", (tokenizer.has("END") ? {type: "END"} : "END")], "postprocess": defaultAction("provide-block")},
  {"name": "provide-block_A1_I4?", "symbols": [], "postprocess": inlineAction("provide-block_A1_I4?")},
  {"name": "provide-block_A1_I4?", "symbols": ["provide-block_A1_I4"], "postprocess": inlineAction("provide-block_A1_I4?")},
  {"name": "provide-block_A1_I4", "symbols": ["provide-spec", "provide-block_A1_I4_I1*", "provide-block_A1_I4_I2?"], "postprocess": inlineAction("provide-block_A1_I4")},
  {"name": "provide-block_A1_I4_I1*", "symbols": [], "postprocess": inlineAction("provide-block_A1_I4_I1*")},
  {"name": "provide-block_A1_I4_I1*", "symbols": ["provide-block_A1_I4_I1*", "provide-block_A1_I4_I1"], "postprocess": listSnocAction("provide-block_A1_I4_I1*", "provide-block_A1_I4_I1", true)},
  {"name": "provide-block_A1_I4_I1", "symbols": [(tokenizer.has("COMMA") ? {type: "COMMA"} : "COMMA"), "provide-spec"], "postprocess": inlineAction("provide-block_A1_I4_I1")},
  {"name": "provide-block_A1_I4_I2?", "symbols": [], "postprocess": inlineAction("provide-block_A1_I4_I2?")},
  {"name": "provide-block_A1_I4_I2?", "symbols": ["provide-block_A1_I4_I2"], "postprocess": inlineAction("provide-block_A1_I4_I2?")},
  {"name": "provide-block_A1_I4_I2", "symbols": [(tokenizer.has("COMMA") ? {type: "COMMA"} : "COMMA")], "postprocess": inlineAction("provide-block_A1_I4_I2")},
  {"name": "provide-spec", "symbols": ["provide-name-spec"], "postprocess": defaultAction("provide-spec")},
  {"name": "provide-spec", "symbols": ["provide-type-spec"], "postprocess": defaultAction("provide-spec")},
  {"name": "provide-spec", "symbols": ["provide-data-spec"], "postprocess": defaultAction("provide-spec")},
  {"name": "provide-spec", "symbols": ["provide-module-spec"], "postprocess": defaultAction("provide-spec")},
  {"name": "name-spec", "symbols": ["name-spec_A0_I0", "name-spec_A0_I1?"], "postprocess": defaultAction("name-spec")},
  {"name": "name-spec_A0_I0", "symbols": [(tokenizer.has("STAR") ? {type: "STAR"} : "STAR")], "postprocess": inlineAction("name-spec_A0_I0")},
  {"name": "name-spec_A0_I0", "symbols": [(tokenizer.has("TIMES") ? {type: "TIMES"} : "TIMES")], "postprocess": inlineAction("name-spec_A0_I0")},
  {"name": "name-spec_A0_I1?", "symbols": [], "postprocess": inlineAction("name-spec_A0_I1?")},
  {"name": "name-spec_A0_I1?", "symbols": ["name-spec_A0_I1"], "postprocess": inlineAction("name-spec_A0_I1?")},
  {"name": "name-spec_A0_I1", "symbols": ["hiding-spec"], "postprocess": inlineAction("name-spec_A0_I1")},
  {"name": "name-spec", "symbols": ["module-ref"], "postprocess": defaultAction("name-spec")},
  {"name": "name-spec", "symbols": ["module-ref", (tokenizer.has("AS") ? {type: "AS"} : "AS"), (tokenizer.has("NAME") ? {type: "NAME"} : "NAME")], "postprocess": defaultAction("name-spec")},
  {"name": "data-name-spec", "symbols": ["data-name-spec_A0_I0"], "postprocess": defaultAction("data-name-spec")},
  {"name": "data-name-spec_A0_I0", "symbols": [(tokenizer.has("STAR") ? {type: "STAR"} : "STAR")], "postprocess": inlineAction("data-name-spec_A0_I0")},
  {"name": "data-name-spec_A0_I0", "symbols": [(tokenizer.has("TIMES") ? {type: "TIMES"} : "TIMES")], "postprocess": inlineAction("data-name-spec_A0_I0")},
  {"name": "data-name-spec", "symbols": ["module-ref"], "postprocess": defaultAction("data-name-spec")},
  {"name": "provide-name-spec", "symbols": ["name-spec"], "postprocess": defaultAction("provide-name-spec")},
  {"name": "provide-type-spec", "symbols": [(tokenizer.has("TYPE") ? {type: "TYPE"} : "TYPE"), "name-spec"], "postprocess": defaultAction("provide-type-spec")},
  {"name": "provide-data-spec", "symbols": [(tokenizer.has("DATA") ? {type: "DATA"} : "DATA"), "data-name-spec", "provide-data-spec_I2?"], "postprocess": defaultAction("provide-data-spec")},
  {"name": "provide-data-spec_I2?", "symbols": [], "postprocess": inlineAction("provide-data-spec_I2?")},
  {"name": "provide-data-spec_I2?", "symbols": ["provide-data-spec_I2"], "postprocess": inlineAction("provide-data-spec_I2?")},
  {"name": "provide-data-spec_I2", "symbols": ["hiding-spec"], "postprocess": inlineAction("provide-data-spec_I2")},
  {"name": "provide-module-spec", "symbols": [(tokenizer.has("MODULE") ? {type: "MODULE"} : "MODULE"), "name-spec"], "postprocess": defaultAction("provide-module-spec")},
  {"name": "hiding-spec", "symbols": [(tokenizer.has("HIDING") ? {type: "HIDING"} : "HIDING"), "hiding-spec_I1", "hiding-spec_I2?", (tokenizer.has("RPAREN") ? {type: "RPAREN"} : "RPAREN")], "postprocess": defaultAction("hiding-spec")},
  {"name": "hiding-spec_I1", "symbols": [(tokenizer.has("PARENSPACE") ? {type: "PARENSPACE"} : "PARENSPACE")], "postprocess": inlineAction("hiding-spec_I1")},
  {"name": "hiding-spec_I1", "symbols": [(tokenizer.has("PARENNOSPACE") ? {type: "PARENNOSPACE"} : "PARENNOSPACE")], "postprocess": inlineAction("hiding-spec_I1")},
  {"name": "hiding-spec_I2?", "symbols": [], "postprocess": inlineAction("hiding-spec_I2?")},
  {"name": "hiding-spec_I2?", "symbols": ["hiding-spec_I2"], "postprocess": inlineAction("hiding-spec_I2?")},
  {"name": "hiding-spec_I2", "symbols": ["hiding-spec_I2_I0*", (tokenizer.has("NAME") ? {type: "NAME"} : "NAME")], "postprocess": inlineAction("hiding-spec_I2")},
  {"name": "hiding-spec_I2_I0*", "symbols": [], "postprocess": inlineAction("hiding-spec_I2_I0*")},
  {"name": "hiding-spec_I2_I0*", "symbols": ["hiding-spec_I2_I0*", "hiding-spec_I2_I0"], "postprocess": listSnocAction("hiding-spec_I2_I0*", "hiding-spec_I2_I0", true)},
  {"name": "hiding-spec_I2_I0", "symbols": [(tokenizer.has("NAME") ? {type: "NAME"} : "NAME"), (tokenizer.has("COMMA") ? {type: "COMMA"} : "COMMA")], "postprocess": inlineAction("hiding-spec_I2_I0")},
  {"name": "module-ref", "symbols": ["module-ref_I0*", (tokenizer.has("NAME") ? {type: "NAME"} : "NAME")], "postprocess": defaultAction("module-ref")},
  {"name": "module-ref_I0*", "symbols": [], "postprocess": inlineAction("module-ref_I0*")},
  {"name": "module-ref_I0*", "symbols": ["module-ref_I0*", "module-ref_I0"], "postprocess": listSnocAction("module-ref_I0*", "module-ref_I0", true)},
  {"name": "module-ref_I0", "symbols": [(tokenizer.has("NAME") ? {type: "NAME"} : "NAME"), (tokenizer.has("DOT") ? {type: "DOT"} : "DOT")], "postprocess": inlineAction("module-ref_I0")},
  {"name": "comma-names", "symbols": [(tokenizer.has("NAME") ? {type: "NAME"} : "NAME"), "comma-names_I1*"], "postprocess": defaultAction("comma-names")},
  {"name": "comma-names_I1*", "symbols": [], "postprocess": inlineAction("comma-names_I1*")},
  {"name": "comma-names_I1*", "symbols": ["comma-names_I1*", "comma-names_I1"], "postprocess": listSnocAction("comma-names_I1*", "comma-names_I1", true)},
  {"name": "comma-names_I1", "symbols": [(tokenizer.has("COMMA") ? {type: "COMMA"} : "COMMA"), (tokenizer.has("NAME") ? {type: "NAME"} : "NAME")], "postprocess": inlineAction("comma-names_I1")},
  {"name": "block", "symbols": ["block_I0*"], "postprocess": defaultAction("block")},
  {"name": "block_I0*", "symbols": [], "postprocess": inlineAction("block_I0*")},
  {"name": "block_I0*", "symbols": ["block_I0*", "block_I0"], "postprocess": listSnocAction("block_I0*", "block_I0", true)},
  {"name": "block_I0", "symbols": ["stmt"], "postprocess": inlineAction("block_I0")},
  {"name": "stmt", "symbols": ["type-expr"], "postprocess": defaultAction("stmt")},
  {"name": "stmt", "symbols": ["newtype-expr"], "postprocess": defaultAction("stmt")},
  {"name": "stmt", "symbols": ["spy-stmt"], "postprocess": defaultAction("stmt")},
  {"name": "stmt", "symbols": ["let-expr"], "postprocess": defaultAction("stmt")},
  {"name": "stmt", "symbols": ["fun-expr"], "postprocess": defaultAction("stmt")},
  {"name": "stmt", "symbols": ["data-expr"], "postprocess": defaultAction("stmt")},
  {"name": "stmt", "symbols": ["when-expr"], "postprocess": defaultAction("stmt")},
  {"name": "stmt", "symbols": ["var-expr"], "postprocess": defaultAction("stmt")},
  {"name": "stmt", "symbols": ["rec-expr"], "postprocess": defaultAction("stmt")},
  {"name": "stmt", "symbols": ["assign-expr"], "postprocess": defaultAction("stmt")},
  {"name": "stmt", "symbols": ["check-test"], "postprocess": defaultAction("stmt")},
  {"name": "stmt", "symbols": ["check-expr"], "postprocess": defaultAction("stmt")},
  {"name": "stmt", "symbols": ["contract-stmt"], "postprocess": defaultAction("stmt")},
  {"name": "spy-stmt", "symbols": [(tokenizer.has("SPY") ? {type: "SPY"} : "SPY"), "spy-stmt_I1?", (tokenizer.has("COLON") ? {type: "COLON"} : "COLON"), "spy-stmt_I3?", (tokenizer.has("END") ? {type: "END"} : "END")], "postprocess": defaultAction("spy-stmt")},
  {"name": "spy-stmt_I1?", "symbols": [], "postprocess": inlineAction("spy-stmt_I1?")},
  {"name": "spy-stmt_I1?", "symbols": ["spy-stmt_I1"], "postprocess": inlineAction("spy-stmt_I1?")},
  {"name": "spy-stmt_I1", "symbols": ["binop-expr"], "postprocess": inlineAction("spy-stmt_I1")},
  {"name": "spy-stmt_I3?", "symbols": [], "postprocess": inlineAction("spy-stmt_I3?")},
  {"name": "spy-stmt_I3?", "symbols": ["spy-stmt_I3"], "postprocess": inlineAction("spy-stmt_I3?")},
  {"name": "spy-stmt_I3", "symbols": ["spy-contents"], "postprocess": inlineAction("spy-stmt_I3")},
  {"name": "spy-contents", "symbols": ["spy-field", "spy-contents_I1*"], "postprocess": defaultAction("spy-contents")},
  {"name": "spy-contents_I1*", "symbols": [], "postprocess": inlineAction("spy-contents_I1*")},
  {"name": "spy-contents_I1*", "symbols": ["spy-contents_I1*", "spy-contents_I1"], "postprocess": listSnocAction("spy-contents_I1*", "spy-contents_I1", true)},
  {"name": "spy-contents_I1", "symbols": [(tokenizer.has("COMMA") ? {type: "COMMA"} : "COMMA"), "spy-field"], "postprocess": inlineAction("spy-contents_I1")},
  {"name": "spy-field", "symbols": ["id-expr"], "postprocess": defaultAction("spy-field")},
  {"name": "spy-field", "symbols": [(tokenizer.has("NAME") ? {type: "NAME"} : "NAME"), (tokenizer.has("COLON") ? {type: "COLON"} : "COLON"), "binop-expr"], "postprocess": defaultAction("spy-field")},
  {"name": "type-expr", "symbols": [(tokenizer.has("TYPE") ? {type: "TYPE"} : "TYPE"), (tokenizer.has("NAME") ? {type: "NAME"} : "NAME"), "ty-params", (tokenizer.has("EQUALS") ? {type: "EQUALS"} : "EQUALS"), "ann"], "postprocess": defaultAction("type-expr")},
  {"name": "newtype-expr", "symbols": [(tokenizer.has("NEWTYPE") ? {type: "NEWTYPE"} : "NEWTYPE"), (tokenizer.has("NAME") ? {type: "NAME"} : "NAME"), (tokenizer.has("AS") ? {type: "AS"} : "AS"), (tokenizer.has("NAME") ? {type: "NAME"} : "NAME")], "postprocess": defaultAction("newtype-expr")},
  {"name": "let-expr", "symbols": ["toplevel-binding", (tokenizer.has("EQUALS") ? {type: "EQUALS"} : "EQUALS"), "binop-expr"], "postprocess": defaultAction("let-expr")},
  {"name": "binding", "symbols": ["name-binding"], "postprocess": defaultAction("binding")},
  {"name": "binding", "symbols": ["tuple-binding"], "postprocess": defaultAction("binding")},
  {"name": "tuple-binding", "symbols": [(tokenizer.has("LBRACE") ? {type: "LBRACE"} : "LBRACE"), "tuple-binding_I1*", "binding", "tuple-binding_I3?", (tokenizer.has("RBRACE") ? {type: "RBRACE"} : "RBRACE"), "tuple-binding_I5?"], "postprocess": defaultAction("tuple-binding")},
  {"name": "tuple-binding_I1*", "symbols": [], "postprocess": inlineAction("tuple-binding_I1*")},
  {"name": "tuple-binding_I1*", "symbols": ["tuple-binding_I1*", "tuple-binding_I1"], "postprocess": listSnocAction("tuple-binding_I1*", "tuple-binding_I1", true)},
  {"name": "tuple-binding_I1", "symbols": ["binding", (tokenizer.has("SEMI") ? {type: "SEMI"} : "SEMI")], "postprocess": inlineAction("tuple-binding_I1")},
  {"name": "tuple-binding_I3?", "symbols": [], "postprocess": inlineAction("tuple-binding_I3?")},
  {"name": "tuple-binding_I3?", "symbols": ["tuple-binding_I3"], "postprocess": inlineAction("tuple-binding_I3?")},
  {"name": "tuple-binding_I3", "symbols": [(tokenizer.has("SEMI") ? {type: "SEMI"} : "SEMI")], "postprocess": inlineAction("tuple-binding_I3")},
  {"name": "tuple-binding_I5?", "symbols": [], "postprocess": inlineAction("tuple-binding_I5?")},
  {"name": "tuple-binding_I5?", "symbols": ["tuple-binding_I5"], "postprocess": inlineAction("tuple-binding_I5?")},
  {"name": "tuple-binding_I5", "symbols": [(tokenizer.has("AS") ? {type: "AS"} : "AS"), "name-binding"], "postprocess": inlineAction("tuple-binding_I5")},
  {"name": "name-binding", "symbols": ["name-binding_I0?", (tokenizer.has("NAME") ? {type: "NAME"} : "NAME"), "name-binding_I2?"], "postprocess": defaultAction("name-binding")},
  {"name": "name-binding_I0?", "symbols": [], "postprocess": inlineAction("name-binding_I0?")},
  {"name": "name-binding_I0?", "symbols": ["name-binding_I0"], "postprocess": inlineAction("name-binding_I0?")},
  {"name": "name-binding_I0", "symbols": [(tokenizer.has("SHADOW") ? {type: "SHADOW"} : "SHADOW")], "postprocess": inlineAction("name-binding_I0")},
  {"name": "name-binding_I2?", "symbols": [], "postprocess": inlineAction("name-binding_I2?")},
  {"name": "name-binding_I2?", "symbols": ["name-binding_I2"], "postprocess": inlineAction("name-binding_I2?")},
  {"name": "name-binding_I2", "symbols": [(tokenizer.has("COLONCOLON") ? {type: "COLONCOLON"} : "COLONCOLON"), "ann"], "postprocess": inlineAction("name-binding_I2")},
  {"name": "toplevel-binding", "symbols": ["binding"], "postprocess": defaultAction("toplevel-binding")},
  {"name": "multi-let-expr", "symbols": [(tokenizer.has("LET") ? {type: "LET"} : "LET"), "let-binding", "multi-let-expr_I2*", "multi-let-expr_I3", "block", (tokenizer.has("END") ? {type: "END"} : "END")], "postprocess": defaultAction("multi-let-expr")},
  {"name": "multi-let-expr_I2*", "symbols": [], "postprocess": inlineAction("multi-let-expr_I2*")},
  {"name": "multi-let-expr_I2*", "symbols": ["multi-let-expr_I2*", "multi-let-expr_I2"], "postprocess": listSnocAction("multi-let-expr_I2*", "multi-let-expr_I2", true)},
  {"name": "multi-let-expr_I2", "symbols": [(tokenizer.has("COMMA") ? {type: "COMMA"} : "COMMA"), "let-binding"], "postprocess": inlineAction("multi-let-expr_I2")},
  {"name": "multi-let-expr_I3", "symbols": [(tokenizer.has("BLOCK") ? {type: "BLOCK"} : "BLOCK")], "postprocess": inlineAction("multi-let-expr_I3")},
  {"name": "multi-let-expr_I3", "symbols": [(tokenizer.has("COLON") ? {type: "COLON"} : "COLON")], "postprocess": inlineAction("multi-let-expr_I3")},
  {"name": "let-binding", "symbols": ["let-expr"], "postprocess": defaultAction("let-binding")},
  {"name": "let-binding", "symbols": ["var-expr"], "postprocess": defaultAction("let-binding")},
  {"name": "letrec-expr", "symbols": [(tokenizer.has("LETREC") ? {type: "LETREC"} : "LETREC"), "let-expr", "letrec-expr_I2*", "letrec-expr_I3", "block", (tokenizer.has("END") ? {type: "END"} : "END")], "postprocess": defaultAction("letrec-expr")},
  {"name": "letrec-expr_I2*", "symbols": [], "postprocess": inlineAction("letrec-expr_I2*")},
  {"name": "letrec-expr_I2*", "symbols": ["letrec-expr_I2*", "letrec-expr_I2"], "postprocess": listSnocAction("letrec-expr_I2*", "letrec-expr_I2", true)},
  {"name": "letrec-expr_I2", "symbols": [(tokenizer.has("COMMA") ? {type: "COMMA"} : "COMMA"), "let-expr"], "postprocess": inlineAction("letrec-expr_I2")},
  {"name": "letrec-expr_I3", "symbols": [(tokenizer.has("BLOCK") ? {type: "BLOCK"} : "BLOCK")], "postprocess": inlineAction("letrec-expr_I3")},
  {"name": "letrec-expr_I3", "symbols": [(tokenizer.has("COLON") ? {type: "COLON"} : "COLON")], "postprocess": inlineAction("letrec-expr_I3")},
  {"name": "type-bind", "symbols": [(tokenizer.has("NAME") ? {type: "NAME"} : "NAME"), "ty-params", (tokenizer.has("EQUALS") ? {type: "EQUALS"} : "EQUALS"), "ann"], "postprocess": defaultAction("type-bind")},
  {"name": "newtype-bind", "symbols": [(tokenizer.has("NEWTYPE") ? {type: "NEWTYPE"} : "NEWTYPE"), (tokenizer.has("NAME") ? {type: "NAME"} : "NAME"), (tokenizer.has("AS") ? {type: "AS"} : "AS"), (tokenizer.has("NAME") ? {type: "NAME"} : "NAME")], "postprocess": defaultAction("newtype-bind")},
  {"name": "type-let-bind", "symbols": ["type-bind"], "postprocess": defaultAction("type-let-bind")},
  {"name": "type-let-bind", "symbols": ["newtype-bind"], "postprocess": defaultAction("type-let-bind")},
  {"name": "type-let-expr", "symbols": [(tokenizer.has("TYPE-LET") ? {type: "TYPE-LET"} : "TYPE-LET"), "type-let-bind", "type-let-expr_I2*", "type-let-expr_I3", "block", (tokenizer.has("END") ? {type: "END"} : "END")], "postprocess": defaultAction("type-let-expr")},
  {"name": "type-let-expr_I2*", "symbols": [], "postprocess": inlineAction("type-let-expr_I2*")},
  {"name": "type-let-expr_I2*", "symbols": ["type-let-expr_I2*", "type-let-expr_I2"], "postprocess": listSnocAction("type-let-expr_I2*", "type-let-expr_I2", true)},
  {"name": "type-let-expr_I2", "symbols": [(tokenizer.has("COMMA") ? {type: "COMMA"} : "COMMA"), "type-let-bind"], "postprocess": inlineAction("type-let-expr_I2")},
  {"name": "type-let-expr_I3", "symbols": [(tokenizer.has("BLOCK") ? {type: "BLOCK"} : "BLOCK")], "postprocess": inlineAction("type-let-expr_I3")},
  {"name": "type-let-expr_I3", "symbols": [(tokenizer.has("COLON") ? {type: "COLON"} : "COLON")], "postprocess": inlineAction("type-let-expr_I3")},
  {"name": "contract-stmt", "symbols": [(tokenizer.has("NAME") ? {type: "NAME"} : "NAME"), (tokenizer.has("COLONCOLON") ? {type: "COLONCOLON"} : "COLONCOLON"), "ty-params", "contract-stmt_I3"], "postprocess": defaultAction("contract-stmt")},
  {"name": "contract-stmt_I3", "symbols": ["ann"], "postprocess": inlineAction("contract-stmt_I3")},
  {"name": "contract-stmt_I3", "symbols": ["noparen-arrow-ann"], "postprocess": inlineAction("contract-stmt_I3")},
  {"name": "fun-expr", "symbols": [(tokenizer.has("FUN") ? {type: "FUN"} : "FUN"), (tokenizer.has("NAME") ? {type: "NAME"} : "NAME"), "fun-header", "fun-expr_I3", "doc-string", "block", "where-clause", (tokenizer.has("END") ? {type: "END"} : "END")], "postprocess": defaultAction("fun-expr")},
  {"name": "fun-expr_I3", "symbols": [(tokenizer.has("BLOCK") ? {type: "BLOCK"} : "BLOCK")], "postprocess": inlineAction("fun-expr_I3")},
  {"name": "fun-expr_I3", "symbols": [(tokenizer.has("COLON") ? {type: "COLON"} : "COLON")], "postprocess": inlineAction("fun-expr_I3")},
  {"name": "fun-header", "symbols": ["ty-params", "args", "return-ann"], "postprocess": defaultAction("fun-header")},
  {"name": "fun-header", "symbols": ["ty-params", "bad-args", "return-ann"], "postprocess": defaultAction("fun-header")},
  {"name": "ty-params", "symbols": ["ty-params_I0?"], "postprocess": defaultAction("ty-params")},
  {"name": "ty-params_I0?", "symbols": [], "postprocess": inlineAction("ty-params_I0?")},
  {"name": "ty-params_I0?", "symbols": ["ty-params_I0"], "postprocess": inlineAction("ty-params_I0?")},
  {"name": "ty-params_I0", "symbols": ["ty-params_I0_I0", "comma-names", "ty-params_I0_I2"], "postprocess": inlineAction("ty-params_I0")},
  {"name": "ty-params_I0_I0", "symbols": [(tokenizer.has("LANGLE") ? {type: "LANGLE"} : "LANGLE")], "postprocess": inlineAction("ty-params_I0_I0")},
  {"name": "ty-params_I0_I0", "symbols": [(tokenizer.has("LT") ? {type: "LT"} : "LT")], "postprocess": inlineAction("ty-params_I0_I0")},
  {"name": "ty-params_I0_I2", "symbols": [(tokenizer.has("RANGLE") ? {type: "RANGLE"} : "RANGLE")], "postprocess": inlineAction("ty-params_I0_I2")},
  {"name": "ty-params_I0_I2", "symbols": [(tokenizer.has("GT") ? {type: "GT"} : "GT")], "postprocess": inlineAction("ty-params_I0_I2")},
  {"name": "args", "symbols": ["args_I0", "args_I1?", (tokenizer.has("RPAREN") ? {type: "RPAREN"} : "RPAREN")], "postprocess": defaultAction("args")},
  {"name": "args_I0", "symbols": [(tokenizer.has("PARENNOSPACE") ? {type: "PARENNOSPACE"} : "PARENNOSPACE")], "postprocess": inlineAction("args_I0")},
  {"name": "args_I0", "symbols": [(tokenizer.has("PARENAFTERBRACE") ? {type: "PARENAFTERBRACE"} : "PARENAFTERBRACE")], "postprocess": inlineAction("args_I0")},
  {"name": "args_I1?", "symbols": [], "postprocess": inlineAction("args_I1?")},
  {"name": "args_I1?", "symbols": ["args_I1"], "postprocess": inlineAction("args_I1?")},
  {"name": "args_I1", "symbols": ["binding", "args_I1_I1*"], "postprocess": inlineAction("args_I1")},
  {"name": "args_I1_I1*", "symbols": [], "postprocess": inlineAction("args_I1_I1*")},
  {"name": "args_I1_I1*", "symbols": ["args_I1_I1*", "args_I1_I1"], "postprocess": listSnocAction("args_I1_I1*", "args_I1_I1", true)},
  {"name": "args_I1_I1", "symbols": [(tokenizer.has("COMMA") ? {type: "COMMA"} : "COMMA"), "binding"], "postprocess": inlineAction("args_I1_I1")},
  {"name": "bad-args", "symbols": [(tokenizer.has("PARENSPACE") ? {type: "PARENSPACE"} : "PARENSPACE"), "bad-args_I1?", (tokenizer.has("RPAREN") ? {type: "RPAREN"} : "RPAREN")], "postprocess": defaultAction("bad-args")},
  {"name": "bad-args_I1?", "symbols": [], "postprocess": inlineAction("bad-args_I1?")},
  {"name": "bad-args_I1?", "symbols": ["bad-args_I1"], "postprocess": inlineAction("bad-args_I1?")},
  {"name": "bad-args_I1", "symbols": ["binding", "bad-args_I1_I1*"], "postprocess": inlineAction("bad-args_I1")},
  {"name": "bad-args_I1_I1*", "symbols": [], "postprocess": inlineAction("bad-args_I1_I1*")},
  {"name": "bad-args_I1_I1*", "symbols": ["bad-args_I1_I1*", "bad-args_I1_I1"], "postprocess": listSnocAction("bad-args_I1_I1*", "bad-args_I1_I1", true)},
  {"name": "bad-args_I1_I1", "symbols": [(tokenizer.has("COMMA") ? {type: "COMMA"} : "COMMA"), "binding"], "postprocess": inlineAction("bad-args_I1_I1")},
  {"name": "return-ann", "symbols": ["return-ann_I0?"], "postprocess": defaultAction("return-ann")},
  {"name": "return-ann_I0?", "symbols": [], "postprocess": inlineAction("return-ann_I0?")},
  {"name": "return-ann_I0?", "symbols": ["return-ann_I0"], "postprocess": inlineAction("return-ann_I0?")},
  {"name": "return-ann_I0", "symbols": [(tokenizer.has("THINARROW") ? {type: "THINARROW"} : "THINARROW"), "ann"], "postprocess": inlineAction("return-ann_I0")},
  {"name": "doc-string", "symbols": ["doc-string_I0?"], "postprocess": defaultAction("doc-string")},
  {"name": "doc-string_I0?", "symbols": [], "postprocess": inlineAction("doc-string_I0?")},
  {"name": "doc-string_I0?", "symbols": ["doc-string_I0"], "postprocess": inlineAction("doc-string_I0?")},
  {"name": "doc-string_I0", "symbols": [(tokenizer.has("DOC") ? {type: "DOC"} : "DOC"), (tokenizer.has("STRING") ? {type: "STRING"} : "STRING")], "postprocess": inlineAction("doc-string_I0")},
  {"name": "where-clause", "symbols": ["where-clause_I0?"], "postprocess": defaultAction("where-clause")},
  {"name": "where-clause_I0?", "symbols": [], "postprocess": inlineAction("where-clause_I0?")},
  {"name": "where-clause_I0?", "symbols": ["where-clause_I0"], "postprocess": inlineAction("where-clause_I0?")},
  {"name": "where-clause_I0", "symbols": [(tokenizer.has("WHERE") ? {type: "WHERE"} : "WHERE"), "block"], "postprocess": inlineAction("where-clause_I0")},
  {"name": "check-expr", "symbols": ["check-expr_A0_I0", (tokenizer.has("STRING") ? {type: "STRING"} : "STRING"), (tokenizer.has("COLON") ? {type: "COLON"} : "COLON"), "block", (tokenizer.has("END") ? {type: "END"} : "END")], "postprocess": defaultAction("check-expr")},
  {"name": "check-expr_A0_I0", "symbols": [(tokenizer.has("CHECK") ? {type: "CHECK"} : "CHECK")], "postprocess": inlineAction("check-expr_A0_I0")},
  {"name": "check-expr_A0_I0", "symbols": [(tokenizer.has("EXAMPLES") ? {type: "EXAMPLES"} : "EXAMPLES")], "postprocess": inlineAction("check-expr_A0_I0")},
  {"name": "check-expr", "symbols": ["check-expr_A1_I0", "block", (tokenizer.has("END") ? {type: "END"} : "END")], "postprocess": defaultAction("check-expr")},
  {"name": "check-expr_A1_I0", "symbols": [(tokenizer.has("CHECKCOLON") ? {type: "CHECKCOLON"} : "CHECKCOLON")], "postprocess": inlineAction("check-expr_A1_I0")},
  {"name": "check-expr_A1_I0", "symbols": [(tokenizer.has("EXAMPLESCOLON") ? {type: "EXAMPLESCOLON"} : "EXAMPLESCOLON")], "postprocess": inlineAction("check-expr_A1_I0")},
  {"name": "check-test", "symbols": ["binop-expr", "check-op", "check-test_A0_I2?", "binop-expr", "check-test_A0_I4?"], "postprocess": defaultAction("check-test")},
  {"name": "check-test_A0_I2?", "symbols": [], "postprocess": inlineAction("check-test_A0_I2?")},
  {"name": "check-test_A0_I2?", "symbols": ["check-test_A0_I2"], "postprocess": inlineAction("check-test_A0_I2?")},
  {"name": "check-test_A0_I2", "symbols": [(tokenizer.has("PERCENT") ? {type: "PERCENT"} : "PERCENT"), "check-test_A0_I2_I1", "binop-expr", (tokenizer.has("RPAREN") ? {type: "RPAREN"} : "RPAREN")], "postprocess": inlineAction("check-test_A0_I2")},
  {"name": "check-test_A0_I2_I1", "symbols": [(tokenizer.has("PARENSPACE") ? {type: "PARENSPACE"} : "PARENSPACE")], "postprocess": inlineAction("check-test_A0_I2_I1")},
  {"name": "check-test_A0_I2_I1", "symbols": [(tokenizer.has("PARENNOSPACE") ? {type: "PARENNOSPACE"} : "PARENNOSPACE")], "postprocess": inlineAction("check-test_A0_I2_I1")},
  {"name": "check-test_A0_I4?", "symbols": [], "postprocess": inlineAction("check-test_A0_I4?")},
  {"name": "check-test_A0_I4?", "symbols": ["check-test_A0_I4"], "postprocess": inlineAction("check-test_A0_I4?")},
  {"name": "check-test_A0_I4", "symbols": [(tokenizer.has("BECAUSE") ? {type: "BECAUSE"} : "BECAUSE"), "binop-expr"], "postprocess": inlineAction("check-test_A0_I4")},
  {"name": "check-test", "symbols": ["binop-expr", "check-op-postfix", "check-test_A1_I2?"], "postprocess": defaultAction("check-test")},
  {"name": "check-test_A1_I2?", "symbols": [], "postprocess": inlineAction("check-test_A1_I2?")},
  {"name": "check-test_A1_I2?", "symbols": ["check-test_A1_I2"], "postprocess": inlineAction("check-test_A1_I2?")},
  {"name": "check-test_A1_I2", "symbols": [(tokenizer.has("BECAUSE") ? {type: "BECAUSE"} : "BECAUSE"), "binop-expr"], "postprocess": inlineAction("check-test_A1_I2")},
  {"name": "check-test", "symbols": ["binop-expr"], "postprocess": defaultAction("check-test")},
  {"name": "data-expr", "symbols": [(tokenizer.has("DATA") ? {type: "DATA"} : "DATA"), (tokenizer.has("NAME") ? {type: "NAME"} : "NAME"), "ty-params", (tokenizer.has("COLON") ? {type: "COLON"} : "COLON"), "data-expr_I4?", "data-expr_I5*", "data-sharing", "where-clause", (tokenizer.has("END") ? {type: "END"} : "END")], "postprocess": defaultAction("data-expr")},
  {"name": "data-expr_I4?", "symbols": [], "postprocess": inlineAction("data-expr_I4?")},
  {"name": "data-expr_I4?", "symbols": ["data-expr_I4"], "postprocess": inlineAction("data-expr_I4?")},
  {"name": "data-expr_I4", "symbols": ["first-data-variant"], "postprocess": inlineAction("data-expr_I4")},
  {"name": "data-expr_I5*", "symbols": [], "postprocess": inlineAction("data-expr_I5*")},
  {"name": "data-expr_I5*", "symbols": ["data-expr_I5*", "data-expr_I5"], "postprocess": listSnocAction("data-expr_I5*", "data-expr_I5", true)},
  {"name": "data-expr_I5", "symbols": ["data-variant"], "postprocess": inlineAction("data-expr_I5")},
  {"name": "variant-constructor", "symbols": [(tokenizer.has("NAME") ? {type: "NAME"} : "NAME"), "variant-members"], "postprocess": defaultAction("variant-constructor")},
  {"name": "first-data-variant", "symbols": ["variant-constructor", "data-with"], "postprocess": defaultAction("first-data-variant")},
  {"name": "first-data-variant", "symbols": [(tokenizer.has("NAME") ? {type: "NAME"} : "NAME"), "data-with"], "postprocess": defaultAction("first-data-variant")},
  {"name": "data-variant", "symbols": [(tokenizer.has("BAR") ? {type: "BAR"} : "BAR"), "variant-constructor", "data-with"], "postprocess": defaultAction("data-variant")},
  {"name": "data-variant", "symbols": [(tokenizer.has("BAR") ? {type: "BAR"} : "BAR"), (tokenizer.has("NAME") ? {type: "NAME"} : "NAME"), "data-with"], "postprocess": defaultAction("data-variant")},
  {"name": "variant-members", "symbols": [(tokenizer.has("PARENNOSPACE") ? {type: "PARENNOSPACE"} : "PARENNOSPACE"), "variant-members_I1?", (tokenizer.has("RPAREN") ? {type: "RPAREN"} : "RPAREN")], "postprocess": defaultAction("variant-members")},
  {"name": "variant-members_I1?", "symbols": [], "postprocess": inlineAction("variant-members_I1?")},
  {"name": "variant-members_I1?", "symbols": ["variant-members_I1"], "postprocess": inlineAction("variant-members_I1?")},
  {"name": "variant-members_I1", "symbols": ["variant-member", "variant-members_I1_I1*"], "postprocess": inlineAction("variant-members_I1")},
  {"name": "variant-members_I1_I1*", "symbols": [], "postprocess": inlineAction("variant-members_I1_I1*")},
  {"name": "variant-members_I1_I1*", "symbols": ["variant-members_I1_I1*", "variant-members_I1_I1"], "postprocess": listSnocAction("variant-members_I1_I1*", "variant-members_I1_I1", true)},
  {"name": "variant-members_I1_I1", "symbols": [(tokenizer.has("COMMA") ? {type: "COMMA"} : "COMMA"), "variant-member"], "postprocess": inlineAction("variant-members_I1_I1")},
  {"name": "variant-member", "symbols": ["variant-member_I0?", "binding"], "postprocess": defaultAction("variant-member")},
  {"name": "variant-member_I0?", "symbols": [], "postprocess": inlineAction("variant-member_I0?")},
  {"name": "variant-member_I0?", "symbols": ["variant-member_I0"], "postprocess": inlineAction("variant-member_I0?")},
  {"name": "variant-member_I0", "symbols": [(tokenizer.has("REF") ? {type: "REF"} : "REF")], "postprocess": inlineAction("variant-member_I0")},
  {"name": "data-with", "symbols": ["data-with_I0?"], "postprocess": defaultAction("data-with")},
  {"name": "data-with_I0?", "symbols": [], "postprocess": inlineAction("data-with_I0?")},
  {"name": "data-with_I0?", "symbols": ["data-with_I0"], "postprocess": inlineAction("data-with_I0?")},
  {"name": "data-with_I0", "symbols": [(tokenizer.has("WITH") ? {type: "WITH"} : "WITH"), "fields"], "postprocess": inlineAction("data-with_I0")},
  {"name": "data-sharing", "symbols": ["data-sharing_I0?"], "postprocess": defaultAction("data-sharing")},
  {"name": "data-sharing_I0?", "symbols": [], "postprocess": inlineAction("data-sharing_I0?")},
  {"name": "data-sharing_I0?", "symbols": ["data-sharing_I0"], "postprocess": inlineAction("data-sharing_I0?")},
  {"name": "data-sharing_I0", "symbols": [(tokenizer.has("SHARING") ? {type: "SHARING"} : "SHARING"), "fields"], "postprocess": inlineAction("data-sharing_I0")},
  {"name": "var-expr", "symbols": [(tokenizer.has("VAR") ? {type: "VAR"} : "VAR"), "toplevel-binding", (tokenizer.has("EQUALS") ? {type: "EQUALS"} : "EQUALS"), "binop-expr"], "postprocess": defaultAction("var-expr")},
  {"name": "rec-expr", "symbols": [(tokenizer.has("REC") ? {type: "REC"} : "REC"), "toplevel-binding", (tokenizer.has("EQUALS") ? {type: "EQUALS"} : "EQUALS"), "binop-expr"], "postprocess": defaultAction("rec-expr")},
  {"name": "assign-expr", "symbols": [(tokenizer.has("NAME") ? {type: "NAME"} : "NAME"), (tokenizer.has("COLONEQUALS") ? {type: "COLONEQUALS"} : "COLONEQUALS"), "binop-expr"], "postprocess": defaultAction("assign-expr")},
  {"name": "when-expr", "symbols": [(tokenizer.has("WHEN") ? {type: "WHEN"} : "WHEN"), "binop-expr", "when-expr_I2", "block", (tokenizer.has("END") ? {type: "END"} : "END")], "postprocess": defaultAction("when-expr")},
  {"name": "when-expr_I2", "symbols": [(tokenizer.has("BLOCK") ? {type: "BLOCK"} : "BLOCK")], "postprocess": inlineAction("when-expr_I2")},
  {"name": "when-expr_I2", "symbols": [(tokenizer.has("COLON") ? {type: "COLON"} : "COLON")], "postprocess": inlineAction("when-expr_I2")},
  {"name": "binop-expr", "symbols": ["expr", "binop-expr_I1*"], "postprocess": defaultAction("binop-expr")},
  {"name": "binop-expr_I1*", "symbols": [], "postprocess": inlineAction("binop-expr_I1*")},
  {"name": "binop-expr_I1*", "symbols": ["binop-expr_I1*", "binop-expr_I1"], "postprocess": listSnocAction("binop-expr_I1*", "binop-expr_I1", true)},
  {"name": "binop-expr_I1", "symbols": ["binop", "expr"], "postprocess": inlineAction("binop-expr_I1")},
  {"name": "binop", "symbols": [(tokenizer.has("PLUS") ? {type: "PLUS"} : "PLUS")], "postprocess": defaultAction("binop")},
  {"name": "binop", "symbols": [(tokenizer.has("DASH") ? {type: "DASH"} : "DASH")], "postprocess": defaultAction("binop")},
  {"name": "binop", "symbols": [(tokenizer.has("TIMES") ? {type: "TIMES"} : "TIMES")], "postprocess": defaultAction("binop")},
  {"name": "binop", "symbols": [(tokenizer.has("SLASH") ? {type: "SLASH"} : "SLASH")], "postprocess": defaultAction("binop")},
  {"name": "binop", "symbols": [(tokenizer.has("LEQ") ? {type: "LEQ"} : "LEQ")], "postprocess": defaultAction("binop")},
  {"name": "binop", "symbols": [(tokenizer.has("GEQ") ? {type: "GEQ"} : "GEQ")], "postprocess": defaultAction("binop")},
  {"name": "binop", "symbols": [(tokenizer.has("EQUALEQUAL") ? {type: "EQUALEQUAL"} : "EQUALEQUAL")], "postprocess": defaultAction("binop")},
  {"name": "binop", "symbols": [(tokenizer.has("SPACESHIP") ? {type: "SPACESHIP"} : "SPACESHIP")], "postprocess": defaultAction("binop")},
  {"name": "binop", "symbols": [(tokenizer.has("EQUALTILDE") ? {type: "EQUALTILDE"} : "EQUALTILDE")], "postprocess": defaultAction("binop")},
  {"name": "binop", "symbols": [(tokenizer.has("NEQ") ? {type: "NEQ"} : "NEQ")], "postprocess": defaultAction("binop")},
  {"name": "binop", "symbols": [(tokenizer.has("LT") ? {type: "LT"} : "LT")], "postprocess": defaultAction("binop")},
  {"name": "binop", "symbols": [(tokenizer.has("GT") ? {type: "GT"} : "GT")], "postprocess": defaultAction("binop")},
  {"name": "binop", "symbols": [(tokenizer.has("AND") ? {type: "AND"} : "AND")], "postprocess": defaultAction("binop")},
  {"name": "binop", "symbols": [(tokenizer.has("OR") ? {type: "OR"} : "OR")], "postprocess": defaultAction("binop")},
  {"name": "binop", "symbols": [(tokenizer.has("CARET") ? {type: "CARET"} : "CARET")], "postprocess": defaultAction("binop")},
  {"name": "check-op", "symbols": [(tokenizer.has("IS") ? {type: "IS"} : "IS")], "postprocess": defaultAction("check-op")},
  {"name": "check-op", "symbols": [(tokenizer.has("ISEQUALEQUAL") ? {type: "ISEQUALEQUAL"} : "ISEQUALEQUAL")], "postprocess": defaultAction("check-op")},
  {"name": "check-op", "symbols": [(tokenizer.has("ISEQUALTILDE") ? {type: "ISEQUALTILDE"} : "ISEQUALTILDE")], "postprocess": defaultAction("check-op")},
  {"name": "check-op", "symbols": [(tokenizer.has("ISSPACESHIP") ? {type: "ISSPACESHIP"} : "ISSPACESHIP")], "postprocess": defaultAction("check-op")},
  {"name": "check-op", "symbols": [(tokenizer.has("ISROUGHLY") ? {type: "ISROUGHLY"} : "ISROUGHLY")], "postprocess": defaultAction("check-op")},
  {"name": "check-op", "symbols": [(tokenizer.has("ISNOT") ? {type: "ISNOT"} : "ISNOT")], "postprocess": defaultAction("check-op")},
  {"name": "check-op", "symbols": [(tokenizer.has("ISNOTEQUALEQUAL") ? {type: "ISNOTEQUALEQUAL"} : "ISNOTEQUALEQUAL")], "postprocess": defaultAction("check-op")},
  {"name": "check-op", "symbols": [(tokenizer.has("ISNOTEQUALTILDE") ? {type: "ISNOTEQUALTILDE"} : "ISNOTEQUALTILDE")], "postprocess": defaultAction("check-op")},
  {"name": "check-op", "symbols": [(tokenizer.has("ISNOTSPACESHIP") ? {type: "ISNOTSPACESHIP"} : "ISNOTSPACESHIP")], "postprocess": defaultAction("check-op")},
  {"name": "check-op", "symbols": [(tokenizer.has("RAISES") ? {type: "RAISES"} : "RAISES")], "postprocess": defaultAction("check-op")},
  {"name": "check-op", "symbols": [(tokenizer.has("RAISESOTHER") ? {type: "RAISESOTHER"} : "RAISESOTHER")], "postprocess": defaultAction("check-op")},
  {"name": "check-op", "symbols": [(tokenizer.has("SATISFIES") ? {type: "SATISFIES"} : "SATISFIES")], "postprocess": defaultAction("check-op")},
  {"name": "check-op", "symbols": [(tokenizer.has("SATISFIESNOT") ? {type: "SATISFIESNOT"} : "SATISFIESNOT")], "postprocess": defaultAction("check-op")},
  {"name": "check-op", "symbols": [(tokenizer.has("RAISESSATISFIES") ? {type: "RAISESSATISFIES"} : "RAISESSATISFIES")], "postprocess": defaultAction("check-op")},
  {"name": "check-op", "symbols": [(tokenizer.has("RAISESVIOLATES") ? {type: "RAISESVIOLATES"} : "RAISESVIOLATES")], "postprocess": defaultAction("check-op")},
  {"name": "check-op-postfix", "symbols": [(tokenizer.has("RAISESNOT") ? {type: "RAISESNOT"} : "RAISESNOT")], "postprocess": defaultAction("check-op-postfix")},
  {"name": "expr", "symbols": ["paren-expr"], "postprocess": defaultAction("expr")},
  {"name": "expr", "symbols": ["id-expr"], "postprocess": defaultAction("expr")},
  {"name": "expr", "symbols": ["prim-expr"], "postprocess": defaultAction("expr")},
  {"name": "expr", "symbols": ["lambda-expr"], "postprocess": defaultAction("expr")},
  {"name": "expr", "symbols": ["method-expr"], "postprocess": defaultAction("expr")},
  {"name": "expr", "symbols": ["app-expr"], "postprocess": defaultAction("expr")},
  {"name": "expr", "symbols": ["obj-expr"], "postprocess": defaultAction("expr")},
  {"name": "expr", "symbols": ["tuple-expr"], "postprocess": defaultAction("expr")},
  {"name": "expr", "symbols": ["tuple-get"], "postprocess": defaultAction("expr")},
  {"name": "expr", "symbols": ["dot-expr"], "postprocess": defaultAction("expr")},
  {"name": "expr", "symbols": ["template-expr"], "postprocess": defaultAction("expr")},
  {"name": "expr", "symbols": ["bracket-expr"], "postprocess": defaultAction("expr")},
  {"name": "expr", "symbols": ["get-bang-expr"], "postprocess": defaultAction("expr")},
  {"name": "expr", "symbols": ["update-expr"], "postprocess": defaultAction("expr")},
  {"name": "expr", "symbols": ["extend-expr"], "postprocess": defaultAction("expr")},
  {"name": "expr", "symbols": ["if-expr"], "postprocess": defaultAction("expr")},
  {"name": "expr", "symbols": ["if-pipe-expr"], "postprocess": defaultAction("expr")},
  {"name": "expr", "symbols": ["cases-expr"], "postprocess": defaultAction("expr")},
  {"name": "expr", "symbols": ["for-expr"], "postprocess": defaultAction("expr")},
  {"name": "expr", "symbols": ["user-block-expr"], "postprocess": defaultAction("expr")},
  {"name": "expr", "symbols": ["inst-expr"], "postprocess": defaultAction("expr")},
  {"name": "expr", "symbols": ["multi-let-expr"], "postprocess": defaultAction("expr")},
  {"name": "expr", "symbols": ["letrec-expr"], "postprocess": defaultAction("expr")},
  {"name": "expr", "symbols": ["type-let-expr"], "postprocess": defaultAction("expr")},
  {"name": "expr", "symbols": ["construct-expr"], "postprocess": defaultAction("expr")},
  {"name": "expr", "symbols": ["table-select"], "postprocess": defaultAction("expr")},
  {"name": "expr", "symbols": ["table-extend"], "postprocess": defaultAction("expr")},
  {"name": "expr", "symbols": ["table-filter"], "postprocess": defaultAction("expr")},
  {"name": "expr", "symbols": ["table-order"], "postprocess": defaultAction("expr")},
  {"name": "expr", "symbols": ["table-extract"], "postprocess": defaultAction("expr")},
  {"name": "expr", "symbols": ["table-update"], "postprocess": defaultAction("expr")},
  {"name": "expr", "symbols": ["table-expr"], "postprocess": defaultAction("expr")},
  {"name": "expr", "symbols": ["load-table-expr"], "postprocess": defaultAction("expr")},
  {"name": "expr", "symbols": ["reactor-expr"], "postprocess": defaultAction("expr")},
  {"name": "template-expr", "symbols": [(tokenizer.has("DOTDOTDOT") ? {type: "DOTDOTDOT"} : "DOTDOTDOT")], "postprocess": defaultAction("template-expr")},
  {"name": "bad-expr", "symbols": [(tokenizer.has("UNTERMINATED-STRING") ? {type: "UNTERMINATED-STRING"} : "UNTERMINATED-STRING")], "postprocess": defaultAction("bad-expr")},
  {"name": "bad-expr", "symbols": [(tokenizer.has("UNTERMINATED-BLOCK-COMMENT") ? {type: "UNTERMINATED-BLOCK-COMMENT"} : "UNTERMINATED-BLOCK-COMMENT")], "postprocess": defaultAction("bad-expr")},
  {"name": "bad-expr", "symbols": [(tokenizer.has("BAD-OPER") ? {type: "BAD-OPER"} : "BAD-OPER")], "postprocess": defaultAction("bad-expr")},
  {"name": "bad-expr", "symbols": [(tokenizer.has("BAD-NUMBER") ? {type: "BAD-NUMBER"} : "BAD-NUMBER")], "postprocess": defaultAction("bad-expr")},
  {"name": "bad-expr", "symbols": [(tokenizer.has("UNKNOWN") ? {type: "UNKNOWN"} : "UNKNOWN")], "postprocess": defaultAction("bad-expr")},
  {"name": "paren-expr", "symbols": ["paren-expr_I0", "binop-expr", (tokenizer.has("RPAREN") ? {type: "RPAREN"} : "RPAREN")], "postprocess": defaultAction("paren-expr")},
  {"name": "paren-expr_I0", "symbols": [(tokenizer.has("PARENSPACE") ? {type: "PARENSPACE"} : "PARENSPACE")], "postprocess": inlineAction("paren-expr_I0")},
  {"name": "paren-expr_I0", "symbols": [(tokenizer.has("PARENAFTERBRACE") ? {type: "PARENAFTERBRACE"} : "PARENAFTERBRACE")], "postprocess": inlineAction("paren-expr_I0")},
  {"name": "id-expr", "symbols": [(tokenizer.has("NAME") ? {type: "NAME"} : "NAME")], "postprocess": defaultAction("id-expr")},
  {"name": "prim-expr", "symbols": ["num-expr"], "postprocess": defaultAction("prim-expr")},
  {"name": "prim-expr", "symbols": ["frac-expr"], "postprocess": defaultAction("prim-expr")},
  {"name": "prim-expr", "symbols": ["rfrac-expr"], "postprocess": defaultAction("prim-expr")},
  {"name": "prim-expr", "symbols": ["bool-expr"], "postprocess": defaultAction("prim-expr")},
  {"name": "prim-expr", "symbols": ["string-expr"], "postprocess": defaultAction("prim-expr")},
  {"name": "num-expr", "symbols": [(tokenizer.has("NUMBER") ? {type: "NUMBER"} : "NUMBER")], "postprocess": defaultAction("num-expr")},
  {"name": "frac-expr", "symbols": [(tokenizer.has("RATIONAL") ? {type: "RATIONAL"} : "RATIONAL")], "postprocess": defaultAction("frac-expr")},
  {"name": "rfrac-expr", "symbols": [(tokenizer.has("ROUGHRATIONAL") ? {type: "ROUGHRATIONAL"} : "ROUGHRATIONAL")], "postprocess": defaultAction("rfrac-expr")},
  {"name": "bool-expr", "symbols": [(tokenizer.has("TRUE") ? {type: "TRUE"} : "TRUE")], "postprocess": defaultAction("bool-expr")},
  {"name": "bool-expr", "symbols": [(tokenizer.has("FALSE") ? {type: "FALSE"} : "FALSE")], "postprocess": defaultAction("bool-expr")},
  {"name": "string-expr", "symbols": [(tokenizer.has("STRING") ? {type: "STRING"} : "STRING")], "postprocess": defaultAction("string-expr")},
  {"name": "lambda-expr", "symbols": [(tokenizer.has("LAM") ? {type: "LAM"} : "LAM"), "fun-header", "lambda-expr_A0_I2", "doc-string", "block", "where-clause", (tokenizer.has("END") ? {type: "END"} : "END")], "postprocess": defaultAction("lambda-expr")},
  {"name": "lambda-expr_A0_I2", "symbols": [(tokenizer.has("BLOCK") ? {type: "BLOCK"} : "BLOCK")], "postprocess": inlineAction("lambda-expr_A0_I2")},
  {"name": "lambda-expr_A0_I2", "symbols": [(tokenizer.has("COLON") ? {type: "COLON"} : "COLON")], "postprocess": inlineAction("lambda-expr_A0_I2")},
  {"name": "lambda-expr", "symbols": [(tokenizer.has("LBRACE") ? {type: "LBRACE"} : "LBRACE"), "fun-header", "lambda-expr_A1_I2", "doc-string", "block", "where-clause", (tokenizer.has("RBRACE") ? {type: "RBRACE"} : "RBRACE")], "postprocess": defaultAction("lambda-expr")},
  {"name": "lambda-expr_A1_I2", "symbols": [(tokenizer.has("BLOCK") ? {type: "BLOCK"} : "BLOCK")], "postprocess": inlineAction("lambda-expr_A1_I2")},
  {"name": "lambda-expr_A1_I2", "symbols": [(tokenizer.has("COLON") ? {type: "COLON"} : "COLON")], "postprocess": inlineAction("lambda-expr_A1_I2")},
  {"name": "method-expr", "symbols": [(tokenizer.has("METHOD") ? {type: "METHOD"} : "METHOD"), "fun-header", "method-expr_I2", "doc-string", "block", "where-clause", (tokenizer.has("END") ? {type: "END"} : "END")], "postprocess": defaultAction("method-expr")},
  {"name": "method-expr_I2", "symbols": [(tokenizer.has("BLOCK") ? {type: "BLOCK"} : "BLOCK")], "postprocess": inlineAction("method-expr_I2")},
  {"name": "method-expr_I2", "symbols": [(tokenizer.has("COLON") ? {type: "COLON"} : "COLON")], "postprocess": inlineAction("method-expr_I2")},
  {"name": "app-expr", "symbols": ["expr", "app-args"], "postprocess": defaultAction("app-expr")},
  {"name": "app-expr", "symbols": ["expr", (tokenizer.has("PARENSPACE") ? {type: "PARENSPACE"} : "PARENSPACE"), (tokenizer.has("RPAREN") ? {type: "RPAREN"} : "RPAREN")], "postprocess": defaultAction("app-expr")},
  {"name": "app-expr", "symbols": ["expr", (tokenizer.has("PARENSPACE") ? {type: "PARENSPACE"} : "PARENSPACE"), "binop-expr", (tokenizer.has("COMMA") ? {type: "COMMA"} : "COMMA"), "binop-expr", "app-expr_A2_I5*", (tokenizer.has("RPAREN") ? {type: "RPAREN"} : "RPAREN")], "postprocess": defaultAction("app-expr")},
  {"name": "app-expr_A2_I5*", "symbols": [], "postprocess": inlineAction("app-expr_A2_I5*")},
  {"name": "app-expr_A2_I5*", "symbols": ["app-expr_A2_I5*", "app-expr_A2_I5"], "postprocess": listSnocAction("app-expr_A2_I5*", "app-expr_A2_I5", true)},
  {"name": "app-expr_A2_I5", "symbols": [(tokenizer.has("COMMA") ? {type: "COMMA"} : "COMMA"), "binop-expr"], "postprocess": inlineAction("app-expr_A2_I5")},
  {"name": "app-args", "symbols": [(tokenizer.has("PARENNOSPACE") ? {type: "PARENNOSPACE"} : "PARENNOSPACE"), "opt-comma-binops", (tokenizer.has("RPAREN") ? {type: "RPAREN"} : "RPAREN")], "postprocess": defaultAction("app-args")},
  {"name": "opt-comma-binops", "symbols": ["opt-comma-binops_I0?"], "postprocess": defaultAction("opt-comma-binops")},
  {"name": "opt-comma-binops_I0?", "symbols": [], "postprocess": inlineAction("opt-comma-binops_I0?")},
  {"name": "opt-comma-binops_I0?", "symbols": ["opt-comma-binops_I0"], "postprocess": inlineAction("opt-comma-binops_I0?")},
  {"name": "opt-comma-binops_I0", "symbols": ["comma-binops"], "postprocess": inlineAction("opt-comma-binops_I0")},
  {"name": "comma-binops", "symbols": ["binop-expr", "comma-binops_I1*"], "postprocess": defaultAction("comma-binops")},
  {"name": "comma-binops_I1*", "symbols": [], "postprocess": inlineAction("comma-binops_I1*")},
  {"name": "comma-binops_I1*", "symbols": ["comma-binops_I1*", "comma-binops_I1"], "postprocess": listSnocAction("comma-binops_I1*", "comma-binops_I1", true)},
  {"name": "comma-binops_I1", "symbols": [(tokenizer.has("COMMA") ? {type: "COMMA"} : "COMMA"), "binop-expr"], "postprocess": inlineAction("comma-binops_I1")},
  {"name": "trailing-opt-comma-binops", "symbols": ["trailing-opt-comma-binops_I0"], "postprocess": defaultAction("trailing-opt-comma-binops")},
  {"name": "trailing-opt-comma-binops_I0", "symbols": ["comma-binops", "trailing-opt-comma-binops_I0_A0_I1?"], "postprocess": inlineAction("trailing-opt-comma-binops_I0")},
  {"name": "trailing-opt-comma-binops_I0_A0_I1?", "symbols": [], "postprocess": inlineAction("trailing-opt-comma-binops_I0_A0_I1?")},
  {"name": "trailing-opt-comma-binops_I0_A0_I1?", "symbols": ["trailing-opt-comma-binops_I0_A0_I1"], "postprocess": inlineAction("trailing-opt-comma-binops_I0_A0_I1?")},
  {"name": "trailing-opt-comma-binops_I0_A0_I1", "symbols": [(tokenizer.has("COMMA") ? {type: "COMMA"} : "COMMA")], "postprocess": inlineAction("trailing-opt-comma-binops_I0_A0_I1")},
  {"name": "trailing-opt-comma-binops_I0", "symbols": [], "postprocess": inlineAction("trailing-opt-comma-binops_I0")},
  {"name": "inst-expr", "symbols": ["expr", (tokenizer.has("LANGLE") ? {type: "LANGLE"} : "LANGLE"), "ann", "inst-expr_I3*", "inst-expr_I4"], "postprocess": defaultAction("inst-expr")},
  {"name": "inst-expr_I3*", "symbols": [], "postprocess": inlineAction("inst-expr_I3*")},
  {"name": "inst-expr_I3*", "symbols": ["inst-expr_I3*", "inst-expr_I3"], "postprocess": listSnocAction("inst-expr_I3*", "inst-expr_I3", true)},
  {"name": "inst-expr_I3", "symbols": [(tokenizer.has("COMMA") ? {type: "COMMA"} : "COMMA"), "ann"], "postprocess": inlineAction("inst-expr_I3")},
  {"name": "inst-expr_I4", "symbols": [(tokenizer.has("RANGLE") ? {type: "RANGLE"} : "RANGLE")], "postprocess": inlineAction("inst-expr_I4")},
  {"name": "inst-expr_I4", "symbols": [(tokenizer.has("GT") ? {type: "GT"} : "GT")], "postprocess": inlineAction("inst-expr_I4")},
  {"name": "tuple-expr", "symbols": [(tokenizer.has("LBRACE") ? {type: "LBRACE"} : "LBRACE"), "tuple-fields", (tokenizer.has("RBRACE") ? {type: "RBRACE"} : "RBRACE")], "postprocess": defaultAction("tuple-expr")},
  {"name": "tuple-fields", "symbols": ["binop-expr", "tuple-fields_I1*", "tuple-fields_I2?"], "postprocess": defaultAction("tuple-fields")},
  {"name": "tuple-fields_I1*", "symbols": [], "postprocess": inlineAction("tuple-fields_I1*")},
  {"name": "tuple-fields_I1*", "symbols": ["tuple-fields_I1*", "tuple-fields_I1"], "postprocess": listSnocAction("tuple-fields_I1*", "tuple-fields_I1", true)},
  {"name": "tuple-fields_I1", "symbols": [(tokenizer.has("SEMI") ? {type: "SEMI"} : "SEMI"), "binop-expr"], "postprocess": inlineAction("tuple-fields_I1")},
  {"name": "tuple-fields_I2?", "symbols": [], "postprocess": inlineAction("tuple-fields_I2?")},
  {"name": "tuple-fields_I2?", "symbols": ["tuple-fields_I2"], "postprocess": inlineAction("tuple-fields_I2?")},
  {"name": "tuple-fields_I2", "symbols": [(tokenizer.has("SEMI") ? {type: "SEMI"} : "SEMI")], "postprocess": inlineAction("tuple-fields_I2")},
  {"name": "tuple-get", "symbols": ["expr", (tokenizer.has("DOT") ? {type: "DOT"} : "DOT"), (tokenizer.has("LBRACE") ? {type: "LBRACE"} : "LBRACE"), (tokenizer.has("NUMBER") ? {type: "NUMBER"} : "NUMBER"), (tokenizer.has("RBRACE") ? {type: "RBRACE"} : "RBRACE")], "postprocess": defaultAction("tuple-get")},
  {"name": "obj-expr", "symbols": [(tokenizer.has("LBRACE") ? {type: "LBRACE"} : "LBRACE"), "obj-fields", (tokenizer.has("RBRACE") ? {type: "RBRACE"} : "RBRACE")], "postprocess": defaultAction("obj-expr")},
  {"name": "obj-expr", "symbols": [(tokenizer.has("LBRACE") ? {type: "LBRACE"} : "LBRACE"), (tokenizer.has("RBRACE") ? {type: "RBRACE"} : "RBRACE")], "postprocess": defaultAction("obj-expr")},
  {"name": "obj-fields", "symbols": ["obj-field", "obj-fields_I1*", "obj-fields_I2?"], "postprocess": defaultAction("obj-fields")},
  {"name": "obj-fields_I1*", "symbols": [], "postprocess": inlineAction("obj-fields_I1*")},
  {"name": "obj-fields_I1*", "symbols": ["obj-fields_I1*", "obj-fields_I1"], "postprocess": listSnocAction("obj-fields_I1*", "obj-fields_I1", true)},
  {"name": "obj-fields_I1", "symbols": [(tokenizer.has("COMMA") ? {type: "COMMA"} : "COMMA"), "obj-field"], "postprocess": inlineAction("obj-fields_I1")},
  {"name": "obj-fields_I2?", "symbols": [], "postprocess": inlineAction("obj-fields_I2?")},
  {"name": "obj-fields_I2?", "symbols": ["obj-fields_I2"], "postprocess": inlineAction("obj-fields_I2?")},
  {"name": "obj-fields_I2", "symbols": [(tokenizer.has("COMMA") ? {type: "COMMA"} : "COMMA")], "postprocess": inlineAction("obj-fields_I2")},
  {"name": "obj-field", "symbols": ["key", (tokenizer.has("COLON") ? {type: "COLON"} : "COLON"), "binop-expr"], "postprocess": defaultAction("obj-field")},
  {"name": "obj-field", "symbols": [(tokenizer.has("REF") ? {type: "REF"} : "REF"), "key", "obj-field_A1_I2?", (tokenizer.has("COLON") ? {type: "COLON"} : "COLON"), "binop-expr"], "postprocess": defaultAction("obj-field")},
  {"name": "obj-field_A1_I2?", "symbols": [], "postprocess": inlineAction("obj-field_A1_I2?")},
  {"name": "obj-field_A1_I2?", "symbols": ["obj-field_A1_I2"], "postprocess": inlineAction("obj-field_A1_I2?")},
  {"name": "obj-field_A1_I2", "symbols": [(tokenizer.has("COLONCOLON") ? {type: "COLONCOLON"} : "COLONCOLON"), "ann"], "postprocess": inlineAction("obj-field_A1_I2")},
  {"name": "obj-field", "symbols": [(tokenizer.has("METHOD") ? {type: "METHOD"} : "METHOD"), "key", "fun-header", "obj-field_A2_I3", "doc-string", "block", "where-clause", (tokenizer.has("END") ? {type: "END"} : "END")], "postprocess": defaultAction("obj-field")},
  {"name": "obj-field_A2_I3", "symbols": [(tokenizer.has("BLOCK") ? {type: "BLOCK"} : "BLOCK")], "postprocess": inlineAction("obj-field_A2_I3")},
  {"name": "obj-field_A2_I3", "symbols": [(tokenizer.has("COLON") ? {type: "COLON"} : "COLON")], "postprocess": inlineAction("obj-field_A2_I3")},
  {"name": "fields", "symbols": ["field", "fields_I1*", "fields_I2?"], "postprocess": defaultAction("fields")},
  {"name": "fields_I1*", "symbols": [], "postprocess": inlineAction("fields_I1*")},
  {"name": "fields_I1*", "symbols": ["fields_I1*", "fields_I1"], "postprocess": listSnocAction("fields_I1*", "fields_I1", true)},
  {"name": "fields_I1", "symbols": [(tokenizer.has("COMMA") ? {type: "COMMA"} : "COMMA"), "field"], "postprocess": inlineAction("fields_I1")},
  {"name": "fields_I2?", "symbols": [], "postprocess": inlineAction("fields_I2?")},
  {"name": "fields_I2?", "symbols": ["fields_I2"], "postprocess": inlineAction("fields_I2?")},
  {"name": "fields_I2", "symbols": [(tokenizer.has("COMMA") ? {type: "COMMA"} : "COMMA")], "postprocess": inlineAction("fields_I2")},
  {"name": "field", "symbols": ["key", (tokenizer.has("COLON") ? {type: "COLON"} : "COLON"), "binop-expr"], "postprocess": defaultAction("field")},
  {"name": "field", "symbols": [(tokenizer.has("METHOD") ? {type: "METHOD"} : "METHOD"), "key", "fun-header", "field_A1_I3", "doc-string", "block", "where-clause", (tokenizer.has("END") ? {type: "END"} : "END")], "postprocess": defaultAction("field")},
  {"name": "field_A1_I3", "symbols": [(tokenizer.has("BLOCK") ? {type: "BLOCK"} : "BLOCK")], "postprocess": inlineAction("field_A1_I3")},
  {"name": "field_A1_I3", "symbols": [(tokenizer.has("COLON") ? {type: "COLON"} : "COLON")], "postprocess": inlineAction("field_A1_I3")},
  {"name": "key", "symbols": [(tokenizer.has("NAME") ? {type: "NAME"} : "NAME")], "postprocess": defaultAction("key")},
  {"name": "construct-expr", "symbols": [(tokenizer.has("LBRACK") ? {type: "LBRACK"} : "LBRACK"), "construct-modifier", "binop-expr", (tokenizer.has("COLON") ? {type: "COLON"} : "COLON"), "trailing-opt-comma-binops", (tokenizer.has("RBRACK") ? {type: "RBRACK"} : "RBRACK")], "postprocess": defaultAction("construct-expr")},
  {"name": "construct-modifier", "symbols": [], "postprocess": defaultAction("construct-modifier")},
  {"name": "construct-modifier", "symbols": [(tokenizer.has("LAZY") ? {type: "LAZY"} : "LAZY")], "postprocess": defaultAction("construct-modifier")},
  {"name": "table-expr", "symbols": [(tokenizer.has("TABLE") ? {type: "TABLE"} : "TABLE"), "table-headers", "table-rows", (tokenizer.has("END") ? {type: "END"} : "END")], "postprocess": defaultAction("table-expr")},
  {"name": "table-headers", "symbols": ["table-headers_I0?"], "postprocess": defaultAction("table-headers")},
  {"name": "table-headers_I0?", "symbols": [], "postprocess": inlineAction("table-headers_I0?")},
  {"name": "table-headers_I0?", "symbols": ["table-headers_I0"], "postprocess": inlineAction("table-headers_I0?")},
  {"name": "table-headers_I0", "symbols": ["table-headers_I0_I0*", "table-header"], "postprocess": inlineAction("table-headers_I0")},
  {"name": "table-headers_I0_I0*", "symbols": [], "postprocess": inlineAction("table-headers_I0_I0*")},
  {"name": "table-headers_I0_I0*", "symbols": ["table-headers_I0_I0*", "table-headers_I0_I0"], "postprocess": listSnocAction("table-headers_I0_I0*", "table-headers_I0_I0", true)},
  {"name": "table-headers_I0_I0", "symbols": ["list-table-header"], "postprocess": inlineAction("table-headers_I0_I0")},
  {"name": "list-table-header", "symbols": ["table-header", (tokenizer.has("COMMA") ? {type: "COMMA"} : "COMMA")], "postprocess": defaultAction("list-table-header")},
  {"name": "table-header", "symbols": [(tokenizer.has("NAME") ? {type: "NAME"} : "NAME"), "table-header_I1?"], "postprocess": defaultAction("table-header")},
  {"name": "table-header_I1?", "symbols": [], "postprocess": inlineAction("table-header_I1?")},
  {"name": "table-header_I1?", "symbols": ["table-header_I1"], "postprocess": inlineAction("table-header_I1?")},
  {"name": "table-header_I1", "symbols": [(tokenizer.has("COLONCOLON") ? {type: "COLONCOLON"} : "COLONCOLON"), "ann"], "postprocess": inlineAction("table-header_I1")},
  {"name": "table-rows", "symbols": ["table-rows_I0?"], "postprocess": defaultAction("table-rows")},
  {"name": "table-rows_I0?", "symbols": [], "postprocess": inlineAction("table-rows_I0?")},
  {"name": "table-rows_I0?", "symbols": ["table-rows_I0"], "postprocess": inlineAction("table-rows_I0?")},
  {"name": "table-rows_I0", "symbols": ["table-rows_I0_I0*", "table-row"], "postprocess": inlineAction("table-rows_I0")},
  {"name": "table-rows_I0_I0*", "symbols": [], "postprocess": inlineAction("table-rows_I0_I0*")},
  {"name": "table-rows_I0_I0*", "symbols": ["table-rows_I0_I0*", "table-rows_I0_I0"], "postprocess": listSnocAction("table-rows_I0_I0*", "table-rows_I0_I0", true)},
  {"name": "table-rows_I0_I0", "symbols": ["table-row"], "postprocess": inlineAction("table-rows_I0_I0")},
  {"name": "table-row", "symbols": [(tokenizer.has("ROW") ? {type: "ROW"} : "ROW"), "table-items"], "postprocess": defaultAction("table-row")},
  {"name": "table-items", "symbols": ["table-items_I0?"], "postprocess": defaultAction("table-items")},
  {"name": "table-items_I0?", "symbols": [], "postprocess": inlineAction("table-items_I0?")},
  {"name": "table-items_I0?", "symbols": ["table-items_I0"], "postprocess": inlineAction("table-items_I0?")},
  {"name": "table-items_I0", "symbols": ["table-items_I0_I0*", "binop-expr"], "postprocess": inlineAction("table-items_I0")},
  {"name": "table-items_I0_I0*", "symbols": [], "postprocess": inlineAction("table-items_I0_I0*")},
  {"name": "table-items_I0_I0*", "symbols": ["table-items_I0_I0*", "table-items_I0_I0"], "postprocess": listSnocAction("table-items_I0_I0*", "table-items_I0_I0", true)},
  {"name": "table-items_I0_I0", "symbols": ["list-table-item"], "postprocess": inlineAction("table-items_I0_I0")},
  {"name": "list-table-item", "symbols": ["binop-expr", (tokenizer.has("COMMA") ? {type: "COMMA"} : "COMMA")], "postprocess": defaultAction("list-table-item")},
  {"name": "reactor-expr", "symbols": [(tokenizer.has("REACTOR") ? {type: "REACTOR"} : "REACTOR"), (tokenizer.has("COLON") ? {type: "COLON"} : "COLON"), "fields", (tokenizer.has("END") ? {type: "END"} : "END")], "postprocess": defaultAction("reactor-expr")},
  {"name": "dot-expr", "symbols": ["expr", (tokenizer.has("DOT") ? {type: "DOT"} : "DOT"), (tokenizer.has("NAME") ? {type: "NAME"} : "NAME")], "postprocess": defaultAction("dot-expr")},
  {"name": "bracket-expr", "symbols": ["expr", (tokenizer.has("LBRACK") ? {type: "LBRACK"} : "LBRACK"), "binop-expr", (tokenizer.has("RBRACK") ? {type: "RBRACK"} : "RBRACK")], "postprocess": defaultAction("bracket-expr")},
  {"name": "get-bang-expr", "symbols": ["expr", (tokenizer.has("BANG") ? {type: "BANG"} : "BANG"), (tokenizer.has("NAME") ? {type: "NAME"} : "NAME")], "postprocess": defaultAction("get-bang-expr")},
  {"name": "extend-expr", "symbols": ["expr", (tokenizer.has("DOT") ? {type: "DOT"} : "DOT"), (tokenizer.has("LBRACE") ? {type: "LBRACE"} : "LBRACE"), "fields", (tokenizer.has("RBRACE") ? {type: "RBRACE"} : "RBRACE")], "postprocess": defaultAction("extend-expr")},
  {"name": "update-expr", "symbols": ["expr", (tokenizer.has("BANG") ? {type: "BANG"} : "BANG"), (tokenizer.has("LBRACE") ? {type: "LBRACE"} : "LBRACE"), "fields", (tokenizer.has("RBRACE") ? {type: "RBRACE"} : "RBRACE")], "postprocess": defaultAction("update-expr")},
  {"name": "if-expr", "symbols": [(tokenizer.has("IF") ? {type: "IF"} : "IF"), "binop-expr", "if-expr_I2", "block", "if-expr_I4*", "if-expr_I5?", (tokenizer.has("END") ? {type: "END"} : "END")], "postprocess": defaultAction("if-expr")},
  {"name": "if-expr_I2", "symbols": [(tokenizer.has("BLOCK") ? {type: "BLOCK"} : "BLOCK")], "postprocess": inlineAction("if-expr_I2")},
  {"name": "if-expr_I2", "symbols": [(tokenizer.has("COLON") ? {type: "COLON"} : "COLON")], "postprocess": inlineAction("if-expr_I2")},
  {"name": "if-expr_I4*", "symbols": [], "postprocess": inlineAction("if-expr_I4*")},
  {"name": "if-expr_I4*", "symbols": ["if-expr_I4*", "if-expr_I4"], "postprocess": listSnocAction("if-expr_I4*", "if-expr_I4", true)},
  {"name": "if-expr_I4", "symbols": ["else-if"], "postprocess": inlineAction("if-expr_I4")},
  {"name": "if-expr_I5?", "symbols": [], "postprocess": inlineAction("if-expr_I5?")},
  {"name": "if-expr_I5?", "symbols": ["if-expr_I5"], "postprocess": inlineAction("if-expr_I5?")},
  {"name": "if-expr_I5", "symbols": [(tokenizer.has("ELSECOLON") ? {type: "ELSECOLON"} : "ELSECOLON"), "block"], "postprocess": inlineAction("if-expr_I5")},
  {"name": "else-if", "symbols": [(tokenizer.has("ELSEIF") ? {type: "ELSEIF"} : "ELSEIF"), "binop-expr", (tokenizer.has("COLON") ? {type: "COLON"} : "COLON"), "block"], "postprocess": defaultAction("else-if")},
  {"name": "if-pipe-expr", "symbols": [(tokenizer.has("ASK") ? {type: "ASK"} : "ASK"), "if-pipe-expr_I1", "if-pipe-expr_I2*", "if-pipe-expr_I3?", (tokenizer.has("END") ? {type: "END"} : "END")], "postprocess": defaultAction("if-pipe-expr")},
  {"name": "if-pipe-expr_I1", "symbols": [(tokenizer.has("BLOCK") ? {type: "BLOCK"} : "BLOCK")], "postprocess": inlineAction("if-pipe-expr_I1")},
  {"name": "if-pipe-expr_I1", "symbols": [(tokenizer.has("COLON") ? {type: "COLON"} : "COLON")], "postprocess": inlineAction("if-pipe-expr_I1")},
  {"name": "if-pipe-expr_I2*", "symbols": [], "postprocess": inlineAction("if-pipe-expr_I2*")},
  {"name": "if-pipe-expr_I2*", "symbols": ["if-pipe-expr_I2*", "if-pipe-expr_I2"], "postprocess": listSnocAction("if-pipe-expr_I2*", "if-pipe-expr_I2", true)},
  {"name": "if-pipe-expr_I2", "symbols": ["if-pipe-branch"], "postprocess": inlineAction("if-pipe-expr_I2")},
  {"name": "if-pipe-expr_I3?", "symbols": [], "postprocess": inlineAction("if-pipe-expr_I3?")},
  {"name": "if-pipe-expr_I3?", "symbols": ["if-pipe-expr_I3"], "postprocess": inlineAction("if-pipe-expr_I3?")},
  {"name": "if-pipe-expr_I3", "symbols": [(tokenizer.has("BAR") ? {type: "BAR"} : "BAR"), (tokenizer.has("OTHERWISECOLON") ? {type: "OTHERWISECOLON"} : "OTHERWISECOLON"), "block"], "postprocess": inlineAction("if-pipe-expr_I3")},
  {"name": "if-pipe-branch", "symbols": [(tokenizer.has("BAR") ? {type: "BAR"} : "BAR"), "binop-expr", (tokenizer.has("THENCOLON") ? {type: "THENCOLON"} : "THENCOLON"), "block"], "postprocess": defaultAction("if-pipe-branch")},
  {"name": "cases-binding", "symbols": ["cases-binding_I0?", "binding"], "postprocess": defaultAction("cases-binding")},
  {"name": "cases-binding_I0?", "symbols": [], "postprocess": inlineAction("cases-binding_I0?")},
  {"name": "cases-binding_I0?", "symbols": ["cases-binding_I0"], "postprocess": inlineAction("cases-binding_I0?")},
  {"name": "cases-binding_I0", "symbols": [(tokenizer.has("REF") ? {type: "REF"} : "REF")], "postprocess": inlineAction("cases-binding_I0")},
  {"name": "cases-args", "symbols": [(tokenizer.has("PARENNOSPACE") ? {type: "PARENNOSPACE"} : "PARENNOSPACE"), "cases-args_I1?", (tokenizer.has("RPAREN") ? {type: "RPAREN"} : "RPAREN")], "postprocess": defaultAction("cases-args")},
  {"name": "cases-args_I1?", "symbols": [], "postprocess": inlineAction("cases-args_I1?")},
  {"name": "cases-args_I1?", "symbols": ["cases-args_I1"], "postprocess": inlineAction("cases-args_I1?")},
  {"name": "cases-args_I1", "symbols": ["cases-binding", "cases-args_I1_I1*"], "postprocess": inlineAction("cases-args_I1")},
  {"name": "cases-args_I1_I1*", "symbols": [], "postprocess": inlineAction("cases-args_I1_I1*")},
  {"name": "cases-args_I1_I1*", "symbols": ["cases-args_I1_I1*", "cases-args_I1_I1"], "postprocess": listSnocAction("cases-args_I1_I1*", "cases-args_I1_I1", true)},
  {"name": "cases-args_I1_I1", "symbols": [(tokenizer.has("COMMA") ? {type: "COMMA"} : "COMMA"), "cases-binding"], "postprocess": inlineAction("cases-args_I1_I1")},
  {"name": "cases-expr", "symbols": [(tokenizer.has("CASES") ? {type: "CASES"} : "CASES"), "cases-expr_I1", "ann", (tokenizer.has("RPAREN") ? {type: "RPAREN"} : "RPAREN"), "binop-expr", "cases-expr_I5", "cases-expr_I6*", "cases-expr_I7?", (tokenizer.has("END") ? {type: "END"} : "END")], "postprocess": defaultAction("cases-expr")},
  {"name": "cases-expr_I1", "symbols": [(tokenizer.has("PARENSPACE") ? {type: "PARENSPACE"} : "PARENSPACE")], "postprocess": inlineAction("cases-expr_I1")},
  {"name": "cases-expr_I1", "symbols": [(tokenizer.has("PARENNOSPACE") ? {type: "PARENNOSPACE"} : "PARENNOSPACE")], "postprocess": inlineAction("cases-expr_I1")},
  {"name": "cases-expr_I5", "symbols": [(tokenizer.has("BLOCK") ? {type: "BLOCK"} : "BLOCK")], "postprocess": inlineAction("cases-expr_I5")},
  {"name": "cases-expr_I5", "symbols": [(tokenizer.has("COLON") ? {type: "COLON"} : "COLON")], "postprocess": inlineAction("cases-expr_I5")},
  {"name": "cases-expr_I6*", "symbols": [], "postprocess": inlineAction("cases-expr_I6*")},
  {"name": "cases-expr_I6*", "symbols": ["cases-expr_I6*", "cases-expr_I6"], "postprocess": listSnocAction("cases-expr_I6*", "cases-expr_I6", true)},
  {"name": "cases-expr_I6", "symbols": ["cases-branch"], "postprocess": inlineAction("cases-expr_I6")},
  {"name": "cases-expr_I7?", "symbols": [], "postprocess": inlineAction("cases-expr_I7?")},
  {"name": "cases-expr_I7?", "symbols": ["cases-expr_I7"], "postprocess": inlineAction("cases-expr_I7?")},
  {"name": "cases-expr_I7", "symbols": [(tokenizer.has("BAR") ? {type: "BAR"} : "BAR"), (tokenizer.has("ELSE") ? {type: "ELSE"} : "ELSE"), (tokenizer.has("THICKARROW") ? {type: "THICKARROW"} : "THICKARROW"), "block"], "postprocess": inlineAction("cases-expr_I7")},
  {"name": "cases-branch", "symbols": [(tokenizer.has("BAR") ? {type: "BAR"} : "BAR"), (tokenizer.has("NAME") ? {type: "NAME"} : "NAME"), "cases-branch_I2?", (tokenizer.has("THICKARROW") ? {type: "THICKARROW"} : "THICKARROW"), "block"], "postprocess": defaultAction("cases-branch")},
  {"name": "cases-branch_I2?", "symbols": [], "postprocess": inlineAction("cases-branch_I2?")},
  {"name": "cases-branch_I2?", "symbols": ["cases-branch_I2"], "postprocess": inlineAction("cases-branch_I2?")},
  {"name": "cases-branch_I2", "symbols": ["cases-args"], "postprocess": inlineAction("cases-branch_I2")},
  {"name": "for-bind", "symbols": ["binding", (tokenizer.has("FROM") ? {type: "FROM"} : "FROM"), "binop-expr"], "postprocess": defaultAction("for-bind")},
  {"name": "for-expr", "symbols": [(tokenizer.has("FOR") ? {type: "FOR"} : "FOR"), "expr", (tokenizer.has("PARENNOSPACE") ? {type: "PARENNOSPACE"} : "PARENNOSPACE"), "for-expr_I3?", (tokenizer.has("RPAREN") ? {type: "RPAREN"} : "RPAREN"), "return-ann", "for-expr_I6", "block", (tokenizer.has("END") ? {type: "END"} : "END")], "postprocess": defaultAction("for-expr")},
  {"name": "for-expr_I3?", "symbols": [], "postprocess": inlineAction("for-expr_I3?")},
  {"name": "for-expr_I3?", "symbols": ["for-expr_I3"], "postprocess": inlineAction("for-expr_I3?")},
  {"name": "for-expr_I3", "symbols": ["for-bind", "for-expr_I3_I1*"], "postprocess": inlineAction("for-expr_I3")},
  {"name": "for-expr_I3_I1*", "symbols": [], "postprocess": inlineAction("for-expr_I3_I1*")},
  {"name": "for-expr_I3_I1*", "symbols": ["for-expr_I3_I1*", "for-expr_I3_I1"], "postprocess": listSnocAction("for-expr_I3_I1*", "for-expr_I3_I1", true)},
  {"name": "for-expr_I3_I1", "symbols": [(tokenizer.has("COMMA") ? {type: "COMMA"} : "COMMA"), "for-bind"], "postprocess": inlineAction("for-expr_I3_I1")},
  {"name": "for-expr_I6", "symbols": [(tokenizer.has("BLOCK") ? {type: "BLOCK"} : "BLOCK")], "postprocess": inlineAction("for-expr_I6")},
  {"name": "for-expr_I6", "symbols": [(tokenizer.has("COLON") ? {type: "COLON"} : "COLON")], "postprocess": inlineAction("for-expr_I6")},
  {"name": "column-order", "symbols": [(tokenizer.has("NAME") ? {type: "NAME"} : "NAME"), "column-order_I1"], "postprocess": defaultAction("column-order")},
  {"name": "column-order_I1", "symbols": [(tokenizer.has("ASCENDING") ? {type: "ASCENDING"} : "ASCENDING")], "postprocess": inlineAction("column-order_I1")},
  {"name": "column-order_I1", "symbols": [(tokenizer.has("DESCENDING") ? {type: "DESCENDING"} : "DESCENDING")], "postprocess": inlineAction("column-order_I1")},
  {"name": "table-select", "symbols": [(tokenizer.has("TABLE-SELECT") ? {type: "TABLE-SELECT"} : "TABLE-SELECT"), (tokenizer.has("NAME") ? {type: "NAME"} : "NAME"), "table-select_I2*", (tokenizer.has("FROM") ? {type: "FROM"} : "FROM"), "expr", (tokenizer.has("END") ? {type: "END"} : "END")], "postprocess": defaultAction("table-select")},
  {"name": "table-select_I2*", "symbols": [], "postprocess": inlineAction("table-select_I2*")},
  {"name": "table-select_I2*", "symbols": ["table-select_I2*", "table-select_I2"], "postprocess": listSnocAction("table-select_I2*", "table-select_I2", true)},
  {"name": "table-select_I2", "symbols": [(tokenizer.has("COMMA") ? {type: "COMMA"} : "COMMA"), (tokenizer.has("NAME") ? {type: "NAME"} : "NAME")], "postprocess": inlineAction("table-select_I2")},
  {"name": "table-filter", "symbols": [(tokenizer.has("TABLE-FILTER") ? {type: "TABLE-FILTER"} : "TABLE-FILTER"), "expr", "table-filter_I2?", (tokenizer.has("COLON") ? {type: "COLON"} : "COLON"), "binop-expr", (tokenizer.has("END") ? {type: "END"} : "END")], "postprocess": defaultAction("table-filter")},
  {"name": "table-filter_I2?", "symbols": [], "postprocess": inlineAction("table-filter_I2?")},
  {"name": "table-filter_I2?", "symbols": ["table-filter_I2"], "postprocess": inlineAction("table-filter_I2?")},
  {"name": "table-filter_I2", "symbols": [(tokenizer.has("USING") ? {type: "USING"} : "USING"), "binding", "table-filter_I2_I2*"], "postprocess": inlineAction("table-filter_I2")},
  {"name": "table-filter_I2_I2*", "symbols": [], "postprocess": inlineAction("table-filter_I2_I2*")},
  {"name": "table-filter_I2_I2*", "symbols": ["table-filter_I2_I2*", "table-filter_I2_I2"], "postprocess": listSnocAction("table-filter_I2_I2*", "table-filter_I2_I2", true)},
  {"name": "table-filter_I2_I2", "symbols": [(tokenizer.has("COMMA") ? {type: "COMMA"} : "COMMA"), "binding"], "postprocess": inlineAction("table-filter_I2_I2")},
  {"name": "table-order", "symbols": [(tokenizer.has("TABLE-ORDER") ? {type: "TABLE-ORDER"} : "TABLE-ORDER"), "expr", (tokenizer.has("COLON") ? {type: "COLON"} : "COLON"), "column-order", "table-order_I4*", (tokenizer.has("END") ? {type: "END"} : "END")], "postprocess": defaultAction("table-order")},
  {"name": "table-order_I4*", "symbols": [], "postprocess": inlineAction("table-order_I4*")},
  {"name": "table-order_I4*", "symbols": ["table-order_I4*", "table-order_I4"], "postprocess": listSnocAction("table-order_I4*", "table-order_I4", true)},
  {"name": "table-order_I4", "symbols": [(tokenizer.has("COMMA") ? {type: "COMMA"} : "COMMA"), "column-order"], "postprocess": inlineAction("table-order_I4")},
  {"name": "table-extract", "symbols": [(tokenizer.has("TABLE-EXTRACT") ? {type: "TABLE-EXTRACT"} : "TABLE-EXTRACT"), (tokenizer.has("NAME") ? {type: "NAME"} : "NAME"), (tokenizer.has("FROM") ? {type: "FROM"} : "FROM"), "expr", (tokenizer.has("END") ? {type: "END"} : "END")], "postprocess": defaultAction("table-extract")},
  {"name": "table-update", "symbols": [(tokenizer.has("TABLE-UPDATE") ? {type: "TABLE-UPDATE"} : "TABLE-UPDATE"), "expr", "table-update_I2?", (tokenizer.has("COLON") ? {type: "COLON"} : "COLON"), "obj-fields", (tokenizer.has("END") ? {type: "END"} : "END")], "postprocess": defaultAction("table-update")},
  {"name": "table-update_I2?", "symbols": [], "postprocess": inlineAction("table-update_I2?")},
  {"name": "table-update_I2?", "symbols": ["table-update_I2"], "postprocess": inlineAction("table-update_I2?")},
  {"name": "table-update_I2", "symbols": [(tokenizer.has("USING") ? {type: "USING"} : "USING"), "binding", "table-update_I2_I2*"], "postprocess": inlineAction("table-update_I2")},
  {"name": "table-update_I2_I2*", "symbols": [], "postprocess": inlineAction("table-update_I2_I2*")},
  {"name": "table-update_I2_I2*", "symbols": ["table-update_I2_I2*", "table-update_I2_I2"], "postprocess": listSnocAction("table-update_I2_I2*", "table-update_I2_I2", true)},
  {"name": "table-update_I2_I2", "symbols": [(tokenizer.has("COMMA") ? {type: "COMMA"} : "COMMA"), "binding"], "postprocess": inlineAction("table-update_I2_I2")},
  {"name": "table-extend", "symbols": [(tokenizer.has("TABLE-EXTEND") ? {type: "TABLE-EXTEND"} : "TABLE-EXTEND"), "expr", "table-extend_I2?", (tokenizer.has("COLON") ? {type: "COLON"} : "COLON"), "table-extend-fields", (tokenizer.has("END") ? {type: "END"} : "END")], "postprocess": defaultAction("table-extend")},
  {"name": "table-extend_I2?", "symbols": [], "postprocess": inlineAction("table-extend_I2?")},
  {"name": "table-extend_I2?", "symbols": ["table-extend_I2"], "postprocess": inlineAction("table-extend_I2?")},
  {"name": "table-extend_I2", "symbols": [(tokenizer.has("USING") ? {type: "USING"} : "USING"), "binding", "table-extend_I2_I2*"], "postprocess": inlineAction("table-extend_I2")},
  {"name": "table-extend_I2_I2*", "symbols": [], "postprocess": inlineAction("table-extend_I2_I2*")},
  {"name": "table-extend_I2_I2*", "symbols": ["table-extend_I2_I2*", "table-extend_I2_I2"], "postprocess": listSnocAction("table-extend_I2_I2*", "table-extend_I2_I2", true)},
  {"name": "table-extend_I2_I2", "symbols": [(tokenizer.has("COMMA") ? {type: "COMMA"} : "COMMA"), "binding"], "postprocess": inlineAction("table-extend_I2_I2")},
  {"name": "table-extend-fields", "symbols": ["table-extend-fields_I0*", "table-extend-field", "table-extend-fields_I2?"], "postprocess": defaultAction("table-extend-fields")},
  {"name": "table-extend-fields_I0*", "symbols": [], "postprocess": inlineAction("table-extend-fields_I0*")},
  {"name": "table-extend-fields_I0*", "symbols": ["table-extend-fields_I0*", "table-extend-fields_I0"], "postprocess": listSnocAction("table-extend-fields_I0*", "table-extend-fields_I0", true)},
  {"name": "table-extend-fields_I0", "symbols": ["list-table-extend-field"], "postprocess": inlineAction("table-extend-fields_I0")},
  {"name": "table-extend-fields_I2?", "symbols": [], "postprocess": inlineAction("table-extend-fields_I2?")},
  {"name": "table-extend-fields_I2?", "symbols": ["table-extend-fields_I2"], "postprocess": inlineAction("table-extend-fields_I2?")},
  {"name": "table-extend-fields_I2", "symbols": [(tokenizer.has("COMMA") ? {type: "COMMA"} : "COMMA")], "postprocess": inlineAction("table-extend-fields_I2")},
  {"name": "list-table-extend-field", "symbols": ["table-extend-field", (tokenizer.has("COMMA") ? {type: "COMMA"} : "COMMA")], "postprocess": defaultAction("list-table-extend-field")},
  {"name": "table-extend-field", "symbols": ["key", "table-extend-field_A0_I1?", (tokenizer.has("COLON") ? {type: "COLON"} : "COLON"), "binop-expr"], "postprocess": defaultAction("table-extend-field")},
  {"name": "table-extend-field_A0_I1?", "symbols": [], "postprocess": inlineAction("table-extend-field_A0_I1?")},
  {"name": "table-extend-field_A0_I1?", "symbols": ["table-extend-field_A0_I1"], "postprocess": inlineAction("table-extend-field_A0_I1?")},
  {"name": "table-extend-field_A0_I1", "symbols": [(tokenizer.has("COLONCOLON") ? {type: "COLONCOLON"} : "COLONCOLON"), "ann"], "postprocess": inlineAction("table-extend-field_A0_I1")},
  {"name": "table-extend-field", "symbols": ["key", "table-extend-field_A1_I1?", (tokenizer.has("COLON") ? {type: "COLON"} : "COLON"), "expr", (tokenizer.has("OF") ? {type: "OF"} : "OF"), (tokenizer.has("NAME") ? {type: "NAME"} : "NAME")], "postprocess": defaultAction("table-extend-field")},
  {"name": "table-extend-field_A1_I1?", "symbols": [], "postprocess": inlineAction("table-extend-field_A1_I1?")},
  {"name": "table-extend-field_A1_I1?", "symbols": ["table-extend-field_A1_I1"], "postprocess": inlineAction("table-extend-field_A1_I1?")},
  {"name": "table-extend-field_A1_I1", "symbols": [(tokenizer.has("COLONCOLON") ? {type: "COLONCOLON"} : "COLONCOLON"), "ann"], "postprocess": inlineAction("table-extend-field_A1_I1")},
  {"name": "load-table-expr", "symbols": [(tokenizer.has("LOAD-TABLE") ? {type: "LOAD-TABLE"} : "LOAD-TABLE"), (tokenizer.has("COLON") ? {type: "COLON"} : "COLON"), "table-headers", "load-table-expr_I3?", (tokenizer.has("END") ? {type: "END"} : "END")], "postprocess": defaultAction("load-table-expr")},
  {"name": "load-table-expr_I3?", "symbols": [], "postprocess": inlineAction("load-table-expr_I3?")},
  {"name": "load-table-expr_I3?", "symbols": ["load-table-expr_I3"], "postprocess": inlineAction("load-table-expr_I3?")},
  {"name": "load-table-expr_I3", "symbols": ["load-table-specs"], "postprocess": inlineAction("load-table-expr_I3")},
  {"name": "load-table-specs", "symbols": ["load-table-specs_I0*", "load-table-spec"], "postprocess": defaultAction("load-table-specs")},
  {"name": "load-table-specs_I0*", "symbols": [], "postprocess": inlineAction("load-table-specs_I0*")},
  {"name": "load-table-specs_I0*", "symbols": ["load-table-specs_I0*", "load-table-specs_I0"], "postprocess": listSnocAction("load-table-specs_I0*", "load-table-specs_I0", true)},
  {"name": "load-table-specs_I0", "symbols": ["load-table-spec"], "postprocess": inlineAction("load-table-specs_I0")},
  {"name": "load-table-spec", "symbols": [(tokenizer.has("SOURCECOLON") ? {type: "SOURCECOLON"} : "SOURCECOLON"), "expr"], "postprocess": defaultAction("load-table-spec")},
  {"name": "load-table-spec", "symbols": [(tokenizer.has("SANITIZE") ? {type: "SANITIZE"} : "SANITIZE"), (tokenizer.has("NAME") ? {type: "NAME"} : "NAME"), (tokenizer.has("USING") ? {type: "USING"} : "USING"), "expr"], "postprocess": defaultAction("load-table-spec")},
  {"name": "user-block-expr", "symbols": [(tokenizer.has("BLOCK") ? {type: "BLOCK"} : "BLOCK"), "block", (tokenizer.has("END") ? {type: "END"} : "END")], "postprocess": defaultAction("user-block-expr")},
  {"name": "ann", "symbols": ["name-ann"], "postprocess": defaultAction("ann")},
  {"name": "ann", "symbols": ["record-ann"], "postprocess": defaultAction("ann")},
  {"name": "ann", "symbols": ["arrow-ann"], "postprocess": defaultAction("ann")},
  {"name": "ann", "symbols": ["app-ann"], "postprocess": defaultAction("ann")},
  {"name": "ann", "symbols": ["pred-ann"], "postprocess": defaultAction("ann")},
  {"name": "ann", "symbols": ["dot-ann"], "postprocess": defaultAction("ann")},
  {"name": "ann", "symbols": ["tuple-ann"], "postprocess": defaultAction("ann")},
  {"name": "name-ann", "symbols": [(tokenizer.has("NAME") ? {type: "NAME"} : "NAME")], "postprocess": defaultAction("name-ann")},
  {"name": "comma-ann-field", "symbols": ["ann-field", "comma-ann-field_I1*"], "postprocess": defaultAction("comma-ann-field")},
  {"name": "comma-ann-field_I1*", "symbols": [], "postprocess": inlineAction("comma-ann-field_I1*")},
  {"name": "comma-ann-field_I1*", "symbols": ["comma-ann-field_I1*", "comma-ann-field_I1"], "postprocess": listSnocAction("comma-ann-field_I1*", "comma-ann-field_I1", true)},
  {"name": "comma-ann-field_I1", "symbols": [(tokenizer.has("COMMA") ? {type: "COMMA"} : "COMMA"), "ann-field"], "postprocess": inlineAction("comma-ann-field_I1")},
  {"name": "trailing-opt-comma-ann-field", "symbols": ["trailing-opt-comma-ann-field_I0"], "postprocess": defaultAction("trailing-opt-comma-ann-field")},
  {"name": "trailing-opt-comma-ann-field_I0", "symbols": ["comma-ann-field", "trailing-opt-comma-ann-field_I0_A0_I1?"], "postprocess": inlineAction("trailing-opt-comma-ann-field_I0")},
  {"name": "trailing-opt-comma-ann-field_I0_A0_I1?", "symbols": [], "postprocess": inlineAction("trailing-opt-comma-ann-field_I0_A0_I1?")},
  {"name": "trailing-opt-comma-ann-field_I0_A0_I1?", "symbols": ["trailing-opt-comma-ann-field_I0_A0_I1"], "postprocess": inlineAction("trailing-opt-comma-ann-field_I0_A0_I1?")},
  {"name": "trailing-opt-comma-ann-field_I0_A0_I1", "symbols": [(tokenizer.has("COMMA") ? {type: "COMMA"} : "COMMA")], "postprocess": inlineAction("trailing-opt-comma-ann-field_I0_A0_I1")},
  {"name": "trailing-opt-comma-ann-field_I0", "symbols": [], "postprocess": inlineAction("trailing-opt-comma-ann-field_I0")},
  {"name": "record-ann", "symbols": [(tokenizer.has("LBRACE") ? {type: "LBRACE"} : "LBRACE"), "trailing-opt-comma-ann-field", (tokenizer.has("RBRACE") ? {type: "RBRACE"} : "RBRACE")], "postprocess": defaultAction("record-ann")},
  {"name": "ann-field", "symbols": [(tokenizer.has("NAME") ? {type: "NAME"} : "NAME"), (tokenizer.has("COLONCOLON") ? {type: "COLONCOLON"} : "COLONCOLON"), "ann"], "postprocess": defaultAction("ann-field")},
  {"name": "tuple-ann", "symbols": [(tokenizer.has("LBRACE") ? {type: "LBRACE"} : "LBRACE"), "ann", "tuple-ann_I2*", "tuple-ann_I3?", (tokenizer.has("RBRACE") ? {type: "RBRACE"} : "RBRACE")], "postprocess": defaultAction("tuple-ann")},
  {"name": "tuple-ann_I2*", "symbols": [], "postprocess": inlineAction("tuple-ann_I2*")},
  {"name": "tuple-ann_I2*", "symbols": ["tuple-ann_I2*", "tuple-ann_I2"], "postprocess": listSnocAction("tuple-ann_I2*", "tuple-ann_I2", true)},
  {"name": "tuple-ann_I2", "symbols": [(tokenizer.has("SEMI") ? {type: "SEMI"} : "SEMI"), "ann"], "postprocess": inlineAction("tuple-ann_I2")},
  {"name": "tuple-ann_I3?", "symbols": [], "postprocess": inlineAction("tuple-ann_I3?")},
  {"name": "tuple-ann_I3?", "symbols": ["tuple-ann_I3"], "postprocess": inlineAction("tuple-ann_I3?")},
  {"name": "tuple-ann_I3", "symbols": [(tokenizer.has("SEMI") ? {type: "SEMI"} : "SEMI")], "postprocess": inlineAction("tuple-ann_I3")},
  {"name": "noparen-arrow-ann", "symbols": ["noparen-arrow-ann_I0?", (tokenizer.has("THINARROW") ? {type: "THINARROW"} : "THINARROW"), "ann"], "postprocess": defaultAction("noparen-arrow-ann")},
  {"name": "noparen-arrow-ann_I0?", "symbols": [], "postprocess": inlineAction("noparen-arrow-ann_I0?")},
  {"name": "noparen-arrow-ann_I0?", "symbols": ["noparen-arrow-ann_I0"], "postprocess": inlineAction("noparen-arrow-ann_I0?")},
  {"name": "noparen-arrow-ann_I0", "symbols": ["arrow-ann-args"], "postprocess": inlineAction("noparen-arrow-ann_I0")},
  {"name": "arrow-ann-args", "symbols": ["comma-anns"], "postprocess": defaultAction("arrow-ann-args")},
  {"name": "arrow-ann-args", "symbols": ["arrow-ann-args_A1_I0", "comma-ann-field", (tokenizer.has("RPAREN") ? {type: "RPAREN"} : "RPAREN")], "postprocess": defaultAction("arrow-ann-args")},
  {"name": "arrow-ann-args_A1_I0", "symbols": [(tokenizer.has("PARENSPACE") ? {type: "PARENSPACE"} : "PARENSPACE")], "postprocess": inlineAction("arrow-ann-args_A1_I0")},
  {"name": "arrow-ann-args_A1_I0", "symbols": [(tokenizer.has("PARENNOSPACE") ? {type: "PARENNOSPACE"} : "PARENNOSPACE")], "postprocess": inlineAction("arrow-ann-args_A1_I0")},
  {"name": "arrow-ann-args_A1_I0", "symbols": [(tokenizer.has("PARENAFTERBRACE") ? {type: "PARENAFTERBRACE"} : "PARENAFTERBRACE")], "postprocess": inlineAction("arrow-ann-args_A1_I0")},
  {"name": "arrow-ann", "symbols": ["arrow-ann_I0", "arrow-ann_I1?", (tokenizer.has("THINARROW") ? {type: "THINARROW"} : "THINARROW"), "ann", (tokenizer.has("RPAREN") ? {type: "RPAREN"} : "RPAREN")], "postprocess": defaultAction("arrow-ann")},
  {"name": "arrow-ann_I0", "symbols": [(tokenizer.has("PARENSPACE") ? {type: "PARENSPACE"} : "PARENSPACE")], "postprocess": inlineAction("arrow-ann_I0")},
  {"name": "arrow-ann_I0", "symbols": [(tokenizer.has("PARENNOSPACE") ? {type: "PARENNOSPACE"} : "PARENNOSPACE")], "postprocess": inlineAction("arrow-ann_I0")},
  {"name": "arrow-ann_I0", "symbols": [(tokenizer.has("PARENAFTERBRACE") ? {type: "PARENAFTERBRACE"} : "PARENAFTERBRACE")], "postprocess": inlineAction("arrow-ann_I0")},
  {"name": "arrow-ann_I1?", "symbols": [], "postprocess": inlineAction("arrow-ann_I1?")},
  {"name": "arrow-ann_I1?", "symbols": ["arrow-ann_I1"], "postprocess": inlineAction("arrow-ann_I1?")},
  {"name": "arrow-ann_I1", "symbols": ["arrow-ann-args"], "postprocess": inlineAction("arrow-ann_I1")},
  {"name": "app-ann", "symbols": ["app-ann_I0", (tokenizer.has("LANGLE") ? {type: "LANGLE"} : "LANGLE"), "comma-anns", "app-ann_I3"], "postprocess": defaultAction("app-ann")},
  {"name": "app-ann_I0", "symbols": ["name-ann"], "postprocess": inlineAction("app-ann_I0")},
  {"name": "app-ann_I0", "symbols": ["dot-ann"], "postprocess": inlineAction("app-ann_I0")},
  {"name": "app-ann_I3", "symbols": [(tokenizer.has("RANGLE") ? {type: "RANGLE"} : "RANGLE")], "postprocess": inlineAction("app-ann_I3")},
  {"name": "app-ann_I3", "symbols": [(tokenizer.has("GT") ? {type: "GT"} : "GT")], "postprocess": inlineAction("app-ann_I3")},
  {"name": "comma-anns", "symbols": ["ann", "comma-anns_I1*"], "postprocess": defaultAction("comma-anns")},
  {"name": "comma-anns_I1*", "symbols": [], "postprocess": inlineAction("comma-anns_I1*")},
  {"name": "comma-anns_I1*", "symbols": ["comma-anns_I1*", "comma-anns_I1"], "postprocess": listSnocAction("comma-anns_I1*", "comma-anns_I1", true)},
  {"name": "comma-anns_I1", "symbols": [(tokenizer.has("COMMA") ? {type: "COMMA"} : "COMMA"), "ann"], "postprocess": inlineAction("comma-anns_I1")},
  {"name": "pred-ann", "symbols": ["ann", (tokenizer.has("PERCENT") ? {type: "PERCENT"} : "PERCENT"), "pred-ann_I2", "id-expr", (tokenizer.has("RPAREN") ? {type: "RPAREN"} : "RPAREN")], "postprocess": defaultAction("pred-ann")},
  {"name": "pred-ann_I2", "symbols": [(tokenizer.has("PARENSPACE") ? {type: "PARENSPACE"} : "PARENSPACE")], "postprocess": inlineAction("pred-ann_I2")},
  {"name": "pred-ann_I2", "symbols": [(tokenizer.has("PARENNOSPACE") ? {type: "PARENNOSPACE"} : "PARENNOSPACE")], "postprocess": inlineAction("pred-ann_I2")},
  {"name": "dot-ann", "symbols": [(tokenizer.has("NAME") ? {type: "NAME"} : "NAME"), (tokenizer.has("DOT") ? {type: "DOT"} : "DOT"), (tokenizer.has("NAME") ? {type: "NAME"} : "NAME")], "postprocess": defaultAction("dot-ann")},
  ],
  ParserStart: "program"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
	module.exports = grammar;
} else {
	window.grammar = grammar;
}
})();
