<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>arr</string>
	</array>
	<key>name</key>
	<string>Pyret</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Delimiters</string>
			<key>match</key>
			<string>(!|-&gt;|=&gt;|:=|\[|\]|{|}|:\s)</string>
			<key>name</key>
			<string>keyword.other.delimiters.arr</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>()</string>
			<key>match</key>
			<string>(\(|\)|\.|::|=)</string>
			<key>name</key>
			<string>variable.arr</string>
		</dict>
		<dict>
			<key>comment</key>
			<false/>
			<key>match</key>
			<string>(\|)</string>
			<key>name</key>
			<string>storage.type.delimiters.arr</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>cases</string>
			<key>match</key>
			<string>(^\s\|) ([a-zA-Z0-9\-]*) (=&gt;)</string>
			<key>name</key>
			<string>variable.arr</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Basic keywords</string>
			<key>match</key>
			<string>\s(fun\s|where:|end\s|type\s|data\b|import\b|provide\b|var\b|fun:\s|with:\s|sharing:\s|as\b|try:\s|except\b|when\b|for\b|from\b|check:\s|where:\s|doc:\s|and\b|or\b| not |else:\s|\sif\s|is==\s|is=~\s|is&lt;=&gt;\s|is-not==\s|is-not=~\s|is-not&lt;=&gt;\s|is-not\b|is\s|raises\b|deriving\b|ref\b|graph:\s|m-graph:\s|block:\s|satisfies\b|shadow\b|\slam\b|type-let\b|provide-types\b|newtype\b|cases)</string>
			<key>name</key>
			<string>keyword.operators.arr</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keywords that start a line</string>
			<key>match</key>
			<string>^(fun\s|where:|end\s|type\s|data\b|import\b|provide\b|check\s|cases)</string>
			<key>name</key>
			<string>keyword.operators.arr</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operators.case.arr</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.arr</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.arr</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>cases</string>
			<key>match</key>
			<string>(cases)\(([a-zA-Z\-&lt;&gt;]*)\) ([a-zA-Z\-]*)(\:)</string>
			<key>name</key>
			<string>variable.operators.arr</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>operators</string>
			<key>match</key>
			<string>( \+ | - | \/ | \* | &gt; | &lt; | &gt;= | &lt;= | &lt;&gt; )</string>
			<key>name</key>
			<string>keyword.operator.arr</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(#\|)</string>
			<key>comment</key>
			<string>multi-line comments</string>
			<key>end</key>
			<string>(\|#)</string>
			<key>name</key>
			<string>string.arr</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>comments</string>
			<key>match</key>
			<string>\#.*$</string>
			<key>name</key>
			<string>comment.line.number-sign.arr</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>comment</key>
			<string>strings</string>
			<key>end</key>
			<string>\"</string>
			<key>name</key>
			<string>string.arr</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\'</string>
			<key>comment</key>
			<string>strings</string>
			<key>end</key>
			<string>\'</string>
			<key>name</key>
			<string>string.arr</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(```)</string>
			<key>comment</key>
			<string>strings</string>
			<key>end</key>
			<string>(```)</string>
			<key>name</key>
			<string>string.arr</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>numbers</string>
			<key>match</key>
			<string>( [0-9]+ )</string>
			<key>name</key>
			<string>constant.numeric.arr</string>
		</dict>
		<dict>
			<key>increaseIndentPattern</key>
			<string>&lt;!--</string>
		</dict>
		<dict>
			<key>decreaseIndentPattern</key>
			<string>(\:)</string>
		</dict>
		<dict>
			<key>highlightPairs</key>
			<string>( ) [ ] { } / /</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.arr</string>
	<key>uuid</key>
	<string>1455576b-4f6f-4650-bc99-ae682419cd2a</string>
</dict>
</plist>
