<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>arr</string>
	</array>
	<key>name</key>
	<string>Pyret</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Delimiters</string>
			<key>match</key>
			<string>(!|\.|\||\(|\)|-&gt;|=|=&gt;|:=|\[|\]|{|}|:|::)</string>
			<key>name</key>
			<string>keyword.other.delimiter.arr</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Now for basic keywords</string>
			<key>match</key>
			<string>\b(var\b|fun\b|fun:\s|end\b|with:\s|sharing:\s|data\b|import\b|provide\b|as\b|try:\s|except\b|when\b|for\b|from\b|check:\s|where:\s|doc:\s|and\b|or\b|not\b|else:\s|if\b|else\b|cases\b|is==\s|is=~\s|is&lt;=&gt;\s|is-not==\s|is-not=~\s|is-not&lt;=&gt;\s|is-not\b|is\s|raises\b|deriving\b|ref\b|graph:\s|m-graph:\s|block:\s|satisfies\b|shadow\b|lam\b|type-let\b|provide-types\b|newtype\b|type\b)</string>
			<key>name</key>
			<string>keyword.control.arr</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>operators</string>
			<key>match</key>
			<string>( \+ | - | \/ | \* | &gt; | &lt; | &gt;= | &lt;= | &lt;&gt; )</string>
			<key>name</key>
			<string>keyword.operator.arr</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>comments</string>
			<key>match</key>
			<string>(\#.*$)</string>
			<key>name</key>
			<string>comment.line.number-sign.arr</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\s\")</string>
			<key>comment</key>
			<string>strings</string>
			<key>end</key>
			<string>(\")</string>
			<key>name</key>
			<string>string.quoted.arr</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\s\')</string>
			<key>comment</key>
			<string>strings</string>
			<key>end</key>
			<string>(\')</string>
			<key>name</key>
			<string>string.quoted.arr</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\s```)</string>
			<key>comment</key>
			<string>strings</string>
			<key>end</key>
			<string>(```)</string>
			<key>name</key>
			<string>string.quoted.arr</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>numbers</string>
			<key>match</key>
			<string>([0-9]+)</string>
			<key>name</key>
			<string>constant.numeric.arr</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.arr</string>
	<key>uuid</key>
	<string>1455576b-4f6f-4650-bc99-ae682419cd2a</string>
</dict>
</plist>
