name: Trigger deploys in drydock

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow in Another Repository
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # GitHub CLI api
          # https://cli.github.com/manual/gh_api
          
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/brownplt/pyret-drydock/dispatches \
             -f 'event_type=trigger-workflow' -F "client_payload[unit]=false" -F "client_payload[integration]=true"
