name: Trigger release deployment

on:
  push:
    branches: [ "release" ]

jobs:
  deploy:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger pyret-release-update in drydock
        env:
          GH_TOKEN: ${{ secrets.DRYDOCK_PAT }}
        run: |
          # GitHub CLI api
          # https://cli.github.com/manual/gh_api

          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/brownplt/pyret-drydock/dispatches \
             -f 'event_type=pyret-release-update' -F "client_payload[unit]=false" -F "client_payload[integration]=true"
