name: Trigger deploys in drydock

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      DRYDOCK_PAT:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow in Another Repository
        env:
          GH_TOKEN: ${{ secrets.DRYDOCK_PAT }}
        run: |
          # GitHub CLI api
          # https://cli.github.com/manual/gh_api

          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/brownplt/pyret-drydock/dispatches \
             -f 'event_type=pyret-lang-update' -F "client_payload[unit]=false" -F "client_payload[integration]=true"
